### ISSUE TITLE
Posible duplicated code in page-header.inc

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#109]
Hello Pat
I think these lines are duplicated in page-header.inc
```
#else if $page == "records"
<h1>$Extras.records_page_header</h1>
```
I found also these lines that might be duplicated too in index.html.tmpl and page-header.inc
```
<div class="wx-stn-info">
        Observations are powered by a <a href="about" target="_blank">Personal Weather 
        Station</a>
</div>
```
Thanks!

**Comment by poblabs** [comment]
> I think these lines are duplicated in page-header.inc
```
 #else if $page == "records"
<h1>$Extras.records_page_header</h1>
```

How so? This says if the page you're viewing is the records page, then show the title from [Extras] for records_page_header which is default to Weather Observation Records. 

Records and reports may look similar, so maybe that is the confusion? Or am I missing something?

---

> I found also these lines that might be duplicated too in index.html.tmpl and page-header.inc
```
 <div class="wx-stn-info">
        Observations are powered by a <a href="about" target="_blank">Personal Weather 
        Station</a>
 </div>
```

This may be duplicated for you if you haven't updated all files recently to the latest development files. In the development branch you can see that in [`index.html.tmpl` it's been replaced with a translatable key](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/index.html.tmpl#L92). And in [`page-header.inc` it's also that same translatable key](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/page-header.inc#L24). 

The index.html.tmpl does not use `page-header.inc`, so that is why `$Extras.powered_by` is used twice.

**Comment by HoracioDos** [comment]
Hello. Perhaps I'm wrong but I still see "records" twice. You know best, please close this issue if it is OK.
```
        <div class="col-sm-5">
            <div class="wx-stn-name">
		#if $page == "graphs"
                <h1>$Extras.graphs_page_header</h1>
		#else if $page == "records"
                <h1>$Extras.records_page_header</h1>
		#else if $page == "reports"
                <h1>$Extras.reports_page_header</h1>
		#else if $page == "records"
                <h1>$Extras.records_page_header</h1>
		#else if $page == "about"
                <h1>$Extras.about_page_header</h1>
		#end if
            </div>
```

**Comment by poblabs** [comment]
Oh I see this now that you have the full thing posted. I didn't catch this earlier. You have better eyes than I do 😃

**Comment by poblabs** [comment]
Fixed!
