### ISSUE TITLE
Weather Observation Graphs - All 

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#123]
The "Today" Graphs are displayed twice on the ALL page.  The remaining buttons display correctly.

![Graph Page  All Button](https://user-images.githubusercontent.com/48191231/57664475-4e59e780-75c6-11e9-9dc2-97b6215c134d.png)

**Comment by poblabs** [comment]
This is probably due to your [homepage] and your [day] graph groups having the same labels.

Hover your mouse over the titles. Do they go to separate graphs?

**Comment by Stormtracker017** [comment]
Pat
No, they both go to the same "day" graph.

Rich

**Comment by poblabs** [comment]
I can tell they are different charts just by the buttons. You have a `Homepage` and a `Day` button. This represents 2 different groups in graphs.conf, or graphs.conf.example.

**Comment by poblabs** [comment]
The data may look the same, because the `[homepage]` and `[day]` graph groups within graphs.conf (or graphs.example.conf if you do not have a graphs.conf) are mirrored groups. 

Feel free to [update your graphs.conf.example with this one](https://raw.githubusercontent.com/poblabs/weewx-belchertown/3cfcd4fcd3b8580520269361964387e75bb8f18c/skins/Belchertown/graphs.conf.example), restart weewx, wait for an archive interval and you should see the titles change. 

If you do not need mirrored groups on homepage, and day, then you can alter the skin.conf option `    highcharts_homepage_graphgroup = "homepage"` to `    highcharts_homepage_graphgroup = "day"` instead (or substitute `day` for the graph group name you wish to display on your home page)

**Comment by Stormtracker017** [comment]
Thanks that corrected the issue.
