### ISSUE TITLE
Edit page-header.inc to remove whitespace where logo would go

### ISSUE THREAD

**Issue by DJ-TrainR3k** [poblabs/weewx-belchertown#128]
Currently with a config file devoid of a site logo, this is what the header section looks like.

![1](https://user-images.githubusercontent.com/13580136/57898384-793e7880-781e-11e9-880a-c0b994f83ad2.png)
___
What I want to do (but cant quite figure out what html and css needs to be changed) is remove the remaining whitespace from the header menu and move it to the main content to make it look more condensed like the edit below.

![2](https://user-images.githubusercontent.com/13580136/57898385-793e7880-781e-11e9-88e9-a30cf400a4f2.png)

It may not look the best, but I think it would look nicer than a big empty white space above the station name. I am also aware that the edited files will need to be backed up before upgrading in the future.

**Comment by HoracioDos** [comment]
Hello DJ:
When there is no logo image, site title is enabled instead.
You could add site_title keyword in weewx.conf or edit it in skin.conf and add a site title
`site_title = "My site Title"`

**Comment by poblabs** [comment]
Horacio's right. The whitespace is where the `site_title` would go. The header is comprised of blocks and that's one of the blocks. 

If you don't want a site title, and no logo, you can collapse the "Example Weather Conditions" upwards - but this would be a custom override and not something I'm supporting at this time. 

Here's how to do it: 

1. Open `skins/Belchertown/style.css`
2. Around line 1377 (as of time of this issue), look for `.wx-stn-name` and add a margin to it like below:
```
.wx-stn-name {
	float:left;
        margin-top: -75px;
}
```
3. Restart weewx for good measure - although you may not have to. 
4. Wait for weewx to run an archive interval which should update the site. 
5. **Make sure you save your style.css (or this how-to) because changes will get overwritten on upgrades. **

It should look like the below:

![image](https://user-images.githubusercontent.com/3484775/57962410-4bbc0280-78e4-11e9-93e0-6c5f51c79e93.png)

If you want to collapse it even more - again I'm not supporting this in an official release, but you can try this CSS:

1. Open style.css again and go to line 1259 (as of time of this issue)
2. Update `.updated-wrapper` to the below:
```
.updated-wrapper {
    float: left;
    margin-top: -34px;
}
```
3. Restart weewx for good measure - although you may not have to. 
4. Wait for weewx to run an archive interval which should update the site. 
5. **Make sure you save your style.css (or this how-to) because changes will get overwritten on upgrades. **

It should look like the below:

![image](https://user-images.githubusercontent.com/3484775/57962433-96d61580-78e4-11e9-9967-58b6b6c7ddeb.png)

Good luck!
