### ISSUE TITLE
Highcharts Wind Rose Tooltip Issue

### ISSUE THREAD

**Issue by Stormtracker017** [poblabs/weewx-belchertown#132]
I don't know if this is a issue with Highland chart, but between "WSW" and "N", the chart covers the Wind Rose. 
[WindRose.zip](https://github.com/poblabs/weewx-belchertown/files/3196115/WindRose.zip)

**Comment by norecords** [comment]
I had the same thought, If you want show value at single time, you have to edit belchertown.js.tmpl
and find at line number 1300 `options.tooltip.shared = true` and set it to `false`

**Comment by poblabs** [comment]
I had done the shared tooltip on the windrose because without it you have to hover over each color to see the value and for the low wind values this can be very hard to do.

However there is a Highcharts tooltip positioner setting that I wasn't aware of until now. So maybe it makes sense to keep it a shared tooltip, but in a location away from the ordinals and their values.

**Comment by poblabs** [comment]
I actually think I solved this in a different way. Using the [tooltip followPointer](https://api.highcharts.com/highcharts/tooltip.followPointer) setting. The tooltip positioner would have worked but it's based on the top left of the chart. So on the homepage it looks good (small chart size) but the graphs page looked bad (wide chart sizes). 

So I'll commit the followPointer update as I think this will solve the issue. You can see the result below. 

![belchertown_windrose_tooltip_followpointer](https://user-images.githubusercontent.com/3484775/58025211-f3eaea80-7ae1-11e9-85eb-696f4e199087.gif)
