### ISSUE TITLE
running 2 instances, sending data to a local server

### ISSUE THREAD

**Issue by slvrscoobie** [poblabs/weewx-belchertown#145]
Im asking here because I know everyone here is really good at figuring out these kinds of issues. 
So I have Belchertown Skin on my WeeWx running on a pi, with a server at 192.168.44.36.
but my external web server is a synology server running webserver on 192.168.44.77.
I added .a second skin to weewx.conf called BelchertownToo which has its html root at 192.168.44.77/web so that I can access my data remotely without VPN into my network and going to the private IP of the Pi. 
but doing so, I get a folder /etc/weewx/192.168.44.77/web 

how do i do what I want to do?? TIA. 

```
[[Belchertown]]
        HTML_ROOT = /var/www/html/weewx/belchertown
        skin = Belchertown
        [[[Extras]]]
            belchertown_root_url = http://192.168.44.36/weewx/belchertown
            forecast_enabled = 1
            
    [[BelchertownToo]]
        HTML_ROOT = 192.168.44.77/web
        skin = Belchertown
        [[[Extras]]]
            belchertown_root_url = http://192.168.44.77/web
            forecast_enabled = 1
```

**Comment by norecords** [comment]
@slvrscoobie 
Hey, It doesn't work like that.. the easiet way is to use FTP or rsync skin to do so, like you can see [here](http://www.weewx.com/docs/usersguide.htm#If_the_server_is_on_a_different_machine)

**Comment by slvrscoobie** [comment]
> @slvrscoobie
> Hey, It doesn't work like that.. the easiet way is to use FTP or rsync skin to do so, like you can see [here](http://www.weewx.com/docs/usersguide.htm#If_the_server_is_on_a_different_machine)
> If 192.168.44.36 can reach 192.168.44.77 I don't see any problem..

well i tried Rsync as it seemed the easiest, but i could Not get it to work. Neither could I get the FTP to work correctly. also - maybe im not understanding the logic of those, but how would I get Belchertown skin to FTP...??

**Comment by poblabs** [comment]
@slvrscoobie This is a tricky one and has come up a couple of times. I think what someone else has done was the 2 skin option but needed to do that because of the `belchertown_root_url` one for the 192.168.x.x and one for http://myhome.whatever.... this also allowed them to show inTemp on the private 192.168 version but not show it on the public version. This works when you have it all running on 1 machine with port forwarding, etc. in place. 

To do what you're doing would require just 1 Belchertown skin, and then you'd want to use the weewx built in [FTP "skin"](http://www.weewx.com/docs/usersguide.htm#config_FTP) or [RSYNC "skin"](http://www.weewx.com/docs/usersguide.htm#config_RSYNC), which then copies the HTML folder to the location you want it.

**Comment by slvrscoobie** [comment]
ah right, I was thinking about this again. so heres the rub:
Locally I cant access my webserver because it redirects to my fios router. So if i put in my myusername.synology.me that DDNS resolves my IP, itll redirect to my router at home. so I have to use the local IP when at home, but everywhere else, i can use the other. So is there a way to set it so I can access it from both locations with one skin?

**Comment by slvrscoobie** [comment]
ahhhh i CAN do it, if it Specify the port :80 - awesome. So Ill try to resolve the FTP issue. set the URL_Root to my external address then i should be able to reach it from anywhere!
