### ISSUE TITLE
Graph with xaxis_categories

### ISSUE THREAD

**Issue by HoracioDos** [poblabs/weewx-belchertown#149]
Hello Pat
Finally "Average Climatological Values for this year" graph started to show something. Main issue was my database, it didn't have two full months of data. (I thought It had at least three months). Now the real issue is that if you don't have records for a full year, graph shows data with wrong month names. It always starts from January when It should start from the month where records are present. Is there some problem with xaxis_categories or it works as it should and I need a full year of records?
Thanks
![CurrentAvgWeather](https://user-images.githubusercontent.com/4549674/58750269-9736ea80-8466-11e9-938e-f1eac28d6c19.png)

**Comment by poblabs** [comment]
This is actually somewhat expected behavior. Since I have no way of controlling the data in your database, and since I don't know what the expected output SHOULD be, this would be up to the user to define those xaxis labels. 

For example, if you run a query on your database, and there's no January, then the skin doesn't know this. It is outputting what it has, then adds those to the groups you have defined.  

So this is something that's left up to the user to know. 

To "fix" this, you just apply a different set of xaxis labels. Like if you are missing January for 2019, you would not include that in `xaxis_categories = 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'`. Then highcharts will just use those labels for the start of your data

**Comment by HoracioDos** [comment]
Excellent!! I suspected that it was the expected behaviour somehow , but I didn't imagine that solution was so simple That's why I didn't want to open this issue as an error. Quite easy to fix! Thanks!

**Comment by poblabs** [comment]
I will add this to the wiki 😃

**Comment by poblabs** [comment]
@HoracioDos Just curious - what happens if you remove `xaxis_categories`? I think it will show the month digits?

**Comment by HoracioDos** [comment]
I'm sorry I was having lunch. You are correct. It shows month numbers: 05 for May, 06 for June

**Comment by poblabs** [comment]
@HoracioDos No worries. And ok good! That can help you (and others) figure out what the categories should be.
