### ISSUE TITLE
Date error on some historic data graphs

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#15]
Just to keep a track of this issue which is being discussed on the weewx forum;

Month charts - end of chart is 1 day ahead of current time
Week charts - end of chart is 1 hour ahead of current time

Today charts are showing correct time

See full transcript of issue raised by Philip Kutzenco on the forum

**Comment by gjr80** [comment]
The cause of the problem is the stop timestamp of the `TimeSpan` object that is passed to `getSqlVectors()`.

For the 'month' plot the aggregate interval used by the supporting `getSqlVectors()` calls is 24 hours, aggregates for each calendar day are obtained by using a start timestamp on a midnight boundary. This is correct but the problem is the stop timestamp of the `TimeSpan` object passed to `getSqlVectors()` is midnight on the 'current' WeeWX day rather than the WeeWX current record timestamp (aka `timespan.stop`). The net effect of this is at that at say 11:00am on 21 December the last aggregate returned by `getSqlVectors()` will cover the timespan 00:00 21 December to 00:00 22 December. The highcharts plots use the stop timestamp of the final aggregate period, in this case 00:00 22 December, as the x-axis value so consequently the plot displays 22 December when it is 11:00 21 December. 

The solution is to make sure that the `TimeSpan` object passed to `getSqlVectors()` has a stop timestamp that is no later than the current record timestamp. This was the case in the original highcharts extension I put together. Use of `time.time()` should be carefully considered because almost certainly the current record timestamp != `time.time()`

A similar approach will likely be needed for anywhere else that `getSqlVectors()` is used ie week and year.

I also suspect that some timestamp formatting may need to be tweaked in some of the tooltips, eg month plots show aggregates for 1 day so the appropriate tooltip time format would be 'd m' or 'd m y' but 'd m H:M` is used.

**Comment by poblabs** [comment]
@gjr80 Thanks for taking the time to explain it! Much appreciated. I tried to get fancy in the fork of your Highcharts extension because of the `timespan` conflicts we were seeing... but since the skins are now split into 2 skins and the compile time seems a lot better, I assume I can revert the highcharts back to the standard `timespan` method. 

The master branch includes a bunch of other changes (0.8rc1 as of this post), so I'll look to revert the `timespan` back for the proper 0.8 release.

**Comment by poblabs** [comment]
I've just pushed commit https://github.com/poblabs/weewx-belchertown/commit/5ac7b8d7165737c2f3ffd7dcfb22fa6fbcb0801d which fixes 2 things: 

1. There was no conversion on rain and rainRate graph values, so metric users weren't being converted properly. Oops. Thanks @gjr80 for some updated code in your repository. Was able to spot what I missed - in fact I was able to update the whole rain portions all together. 
2. I reverted back to using timespan and did away with my band-aids from 0.6. 

Please download the file from here: https://github.com/poblabs/weewx-belchertown/blob/5ac7b8d7165737c2f3ffd7dcfb22fa6fbcb0801d/bin/user/belchertown_highchartsSearchX.py 

Click on the Raw link, copy and paste the contents into your `bin/user/belchertown_highchartsSearchX.py`

Let me know if this fixes things up for you.

**Comment by 41south** [comment]
Have downloaded and copied this file to my /usr/share/weewx/user directory but the errors still appear. Did I need to restart? Daily graphs fine, Week still about an hour ahead, Month as attached
![screen shot 2018-10-01 at 1 04 03 pm](https://user-images.githubusercontent.com/1725001/46264645-aa15ba00-c57b-11e8-83bc-f8ddaf410a0b.png)

**Comment by gjr80** [comment]
Yes. Simple rule of thumb; change weewx.conf you need to do a config reload
or restart, change a. py you need to restart, change a skin you need to
nothing but wait.

**Comment by 41south** [comment]
Done. So in month graphs I have now 2 different things happening at the end of the graph, see attached for rain which has a time scale and baro which is still looking into the future (taken at 1700)
![screen shot 2018-10-01 at 4 58 39 pm](https://user-images.githubusercontent.com/1725001/46269140-98440f00-c59b-11e8-9507-47e853902ff9.png)
![screen shot 2018-10-01 at 4 58 49 pm](https://user-images.githubusercontent.com/1725001/46269141-98440f00-c59b-11e8-8011-e565064f40e6.png)

**Comment by 41south** [comment]
Who new you could zoom :) I've also just noticed that my charts haven't been updating since I installed that version, there is an error in the syslog that I suspect is now rectified with releases since then?

Oct  3 11:05:21 raspberrypi weewx[22729]:         ****  invalid syntax (belchertown_highchartsSearchX.py, line 9)
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****  Traceback (most recent call last):
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      obj.start()
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      self.run()
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 155, in run
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      self.initExtensions(gen_dict[section_name])
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 197, in initExtensions
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      class_ = weeutil.weeutil._get_object(x)
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1132, in _get_object
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      mod = __import__(module)
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****    File "/usr/share/weewx/user/belchertown_highchartsSearchX.py", line 9
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      <!DOCTYPE html>
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****      ^
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****  SyntaxError: invalid syntax
Oct  3 11:05:21 raspberrypi weewx[22729]:         ****  Generator terminated
Oct  3 11:05:21 raspberrypi weewx[22729]: copygenerator: copied 0 files to /var/www/html/weewx/belchertown

**Comment by poblabs** [comment]
Hmm didn't tell me much. Have you updated all files from master or do you
have a mix of 0.7 and recent update files?

**Comment by poblabs** [comment]
Sorry I'm mobile. There is an error there I can look at but first update to
the latest version of the file since I made changes to it a few hours ago.

**Comment by 41south** [comment]
I downloaded that version about 30mins ago so it's the latest. Ah, yes I do have a mix then. 0.7 plus that highcharts file. It may be a couple of days until I can do a complete download and update if that's required as I'm travelling

**Comment by poblabs** [comment]
No, I don't think you need to download everything.... I'm back on PC and see that the error is on line 9. [That's a comment in the code](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown_highchartsSearchX.py#L9), so it should be ignored - so I'm not sure why it's saying you don't have that. 

Have you done a weewx restart since loading it?

**Comment by 41south** [comment]
Yes, that was post restart

**Comment by poblabs** [comment]
The error is confusing because it's erroring on something that isn't being processed. That said, I am running into a new issue now with the rain graph that I didn't catch earlier. I wonder if it's related to your error. Trying to work through it.

**Comment by 41south** [comment]
Is this what I should be seeing inside that file when I nano it?
![screen shot 2018-10-03 at 7 54 45 am](https://user-images.githubusercontent.com/1725001/46383189-b156d800-c6e1-11e8-90cb-843fee605673.png)

**Comment by poblabs** [comment]
Ah that's the problem. You don't want to view source on the new file. You
want to click the raw button and then copy that raw file.

**Comment by 41south** [comment]
Yeah - just figured that out, my bad, sorry! In the process of fixing it now

**Comment by gjr80** [comment]
GitHub does not make it particularly easy to download the source of a single file. Copying and pasting the raw content works, sometimes I find using `wget` to download the source directly to an internet connected host is handy as well, eg:
```
$ wget -P /var/tmp https://raw.githubusercontent.com/poblabs/weewx-belchertown/master/bin/user/belchertown_highchartsSearchX.py
```
the `-P` specifies the destination directory and the URL is the location of the raw source file (usually what you see in your browsers address bar when viewing the raw file).

**Comment by poblabs** [comment]
@gjr80 That'll work too. Gary, do you know of a way to get around any values that have a None or "" when using `getSqlVectors`? For example:

```
        # Get our rain vector for total accumulation
        (time_start_vt, time_stop_vt, rain_vt) = db_lookup().getSqlVectors(TimeSpan(_start_ts, _end_ts), 'rain')
        # Remove any Nones and "" from the rain vector before converting
        # Convert our rain vector
        rain_vt = self.generator.converter.convert(rain_vt)
```

If any value in rain_vt[0] is None or "", then the converter will throw an error `TypeError: can't multiply sequence by non-int of type 'float'`. 

Do I have to break apart the tuple, clean up the None and "", then re-built a new tuple? I've tried various other methods and there doesn't seem to be a good clean Pythonic way.

**Comment by gjr80** [comment]
> If any value in rain_vt[0] is None or "", then the converter will throw an error TypeError: can't multiply sequence by non-int of type 'float'.

@poblabs Can you show me the full stack trace please

**Comment by poblabs** [comment]
@gjr80 here you go:

```
root@weewxapt:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 158, in run
    ngen = self.generate(gen_dict[section_name], self.gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 232, in generate
    ngen += self.generate(section[subsection], gen_ts)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 320, in generate
    default_binding)
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 372, in _getSearchList
    searchList += obj.get_extension_list(timespan, db_lookup)
  File "/usr/share/weewx/user/belchertown_highchartsSearchX.py", line 149, in get_extension_list
    rain_vt = self.generator.converter.convert(rain_vt)
  File "/usr/share/weewx/weewx/units.py", line 764, in convert
    new_val_t = convert(val_t, new_unit_type)
  File "/usr/share/weewx/weewx/units.py", line 1091, in convert
    new_val = conversion_func(val_t[0]) if val_t[0] is not None else None
  File "/usr/share/weewx/weewx/units.py", line 246, in <lambda>
    'mm'               : lambda x : x * MM_PER_INCH},
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by gjr80** [comment]
I'm a bit lost here. Do you know what is actually in `rain_vt`, specifically `rain_vt[0]` (aka `rain_vt.value`) when the error is thrown? `rain_vt` is generated by `getSqlVectors()`, I can understand it returning a sequence of `None` values, and of course a sequence of numerics, a single `None` value or a single numeric.  If we had a sequence of `None` values or a single `None` value the 'is not None' at lines 1089 and 1091 would pick that up and prevent a complaint that you can't multiply a `None` type by a float.

The other thing I have in the back of my mind is `wee_reports`; running `wee_reports` can have an adverse effect on some SLEs, it really depends on what the SLE is doing - I have seen cases where times have been problematic. Does a similar error occur when the same report is generated under WeeWX? If so that would rule out `wee_reports`.

I'll run this up in a VM tomorrow and see if I can identify the cause. If you are able to drop `rain_vt[0]` to screen or log that would be handy, don't worry if you can't.

**Comment by poblabs** [comment]
@gjr80 I think I was fabricating an issue by having a rain value as `""` in my database. I don't think that's a valid weewx value. It's either `0.0` or `None`, so in an attempt at trying to cover all bases as possible I went a little too far. I removed the `""` and so far so good. More testing to go.


@41south How is your testing going after downloading the file again?

**Comment by poblabs** [comment]
Any update here @41south? If not, I'll close this one out with the belchertown_highcharts fix.

**Comment by 41south** [comment]
So far as I can tell this is fixed and can be closed - thanks
