### ISSUE TITLE
Any chance to utilize moment-with-locales.js?

### ISSUE THREAD

**Issue by kalju** [poblabs/weewx-belchertown#163]
Hi,

I'm running weewx with your wonderful skin on Synology NAS. Given the limited number of locales and restrictions with installing additional ones can moment-with-locales.js be used instead of moment.js with local server locale detection?

Thanks in advance!

**Comment by poblabs** [comment]
Hi @kalju I'm under the impression that the moment.js file I've included has all the locales built in. 

This was a bit of an easier task for me to implement rather than inserting the locale name in moment.js's file name and hoping I got it right 100% of the time. 

If you don't want to use auto locale detection (which may be a problem on Synology), there's a skin.conf override you can define: `belchertown_locale = "auto"`. replace `"auto"` with `"en_US.UTF-8"` if you want the en_US locale. Then moment.js will use that for it's locale. 

Does this help?

**Comment by kalju** [comment]
Hi @poblabs,

Well, it is a problems to add any additional locales to Synology. 
And unfortunately using the Estonian locale `belchertown_locale = "et_EE.UTF-8"` in results with error:

> Generator terminated
> reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
> Error changing locale to et_EE.UTF-8. This locale may not exist on your system, or you have a typo. For example the correct way to define this skin setting is 'en_US.UTF-8'. The locale also needs to be installed onto your system first before Belchertown Skin can use it. Please check Google on how to install locales onto your system. Or use the default 'auto' locale skin setting. Full error: unsupported locale setting

**Comment by poblabs** [comment]
@kalju This is a problem for you, I understand. 

I use locale for 3 things:
1. Highcharts for the decimal point and thousands separator
2. Moment.js for all the time formatting across the site (highcharts, html, etc)
3. Records page so that the formatting is correct with thousands and decimals. 

* For item 1 above:
If we can't find the Estonia locale, it will error. So I can make a new option in skin.conf for `locale_decimal = "auto"` or it can be overridden by `= ","` or something similar. I will need to do the same thing with `locale_thousandsSep`.

* For item 2:
moment-with-locales.js will fix this

* For item 3: 
This would be Python looking to do the localization. Since one won't be found, there could be unexpected results. In my testing with Estonia locale - which I do not have installed - the skin runs fine it seems. I just don't know what other problems it could cause? 

Do you want to beta test this and see how it goes for you?

**Comment by poblabs** [comment]
Yeah more testing is showing me that as expected there is a mis-match on the JavaScript items vs. the Python items. Python doesn't have a great way to override the locale number formatting globally. 

So this isn't an ideal situation. Is there no Estonia locale for the Synology?

**Comment by poblabs** [comment]
Another question, do you use the Season skin? Is that representing your
locale?

**Comment by kalju** [comment]
The list of "official" locales on Synology (DSM 6.2) is as follows:
```
root@iNAS:/# locale -a
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8
```
Can not find any recent guides on how to add additional locales to newer versions of Synology (I have 916+).

Seasons skin does not show the estonian locale as well.

The problem for me is the time formatting.

**Comment by HoracioDos** [comment]
Hello Pat.
If time format is the main problem. It could be addressed changing moments.js formats as desired. Is that correct? I remember that until you implemented the locale feature I changed all formats.

**Comment by poblabs** [comment]
@kalju 
> The problem for me is the time formatting.

Give this a try. Open skins/Belchertown/header.html.tmpl and replace the moment.js with the moment-with-locales.js. Save that file. 

Then open bin/user/belchertown.py and search for this line: https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown.py#L126 and put a # at the front. Then below it type `pass`. 

Save that file and set your locale back to et_EE.UTF-8 and restart weewx. 

If you're OK with the other unexpected behavior, like decimal points not matching and such, then this should fix the time format. 

I'll plan on using the moment-with-locales.js file. 

I'll be offline for the next few hours so hopefully this helps in the meantime!

**Comment by kalju** [comment]
Well, it did not work. Either I made mistake or...

```
weewx[3552]: reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
weewx[3552]:         ****  local variable 'system_locale' referenced before assignment
weewx[3552]:         ****  Generator terminated
```

**Comment by poblabs** [comment]
My mistake, 

Instead of `pass`, try this:

`system_locale, locale_encoding = self.generator.skin_dict['Extras']['belchertown_locale'].split(".")`

**Comment by kalju** [comment]
Well, it worked. I now do have et_EE.UTF-8 date formats :-)
Thanks for your help.

Small detail though: header.html.tmpl had moment-with-locales.min.js
I did still replace it with moment-with-locales.js

Closing issue now, good luck with implementing moment-with-locales.js fully!

**Comment by poblabs** [comment]
Thanks! I thought I had included the file! The `.min` is just a minified version which loads faster. 

So this is good. I just need to think about removing that error and forcing the locale (or something)
