### ISSUE TITLE
Chart times are local to viewer, not station

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#17]
I just noticed (viewing from a location 5 hours behind my station) that the highchart times are local to viewer, not the station. The 'data received' date and time for realtime are correct (i.e. local to the station) but highcharts are not

**Comment by poblabs** [comment]
I think this is fixed as of 0.8. Can you confirm?

**Comment by 41south** [comment]
Nope, not yet
![capture](https://user-images.githubusercontent.com/1725001/50457143-553ce080-09be-11e9-9bf2-4da396abff1f.JPG)

**Comment by poblabs** [comment]
What is the timestamp supposed to be? I don't know your offset relative to
the screen shot.

**Comment by 41south** [comment]
Well i would expect to see your local time on the charts - here is Dec 27th 10.51am (GMT +13) which for you I believe is Dec 26th 4.51pm (GMT -5)

**Comment by poblabs** [comment]
Oh that's my chart? Lol guess I didn't look closely

**Comment by 41south** [comment]
Whoops, sorry, yes should have explained better :)

**Comment by poblabs** [comment]
Well, my charts are old code. I haven't been updating my production site,
only the lab site. So I wonder if it's fixed but you're using bad data.

Let me update my stuff and let you check it out.

**Comment by 41south** [comment]
I just had a look at Scotts web site and it's showing me my local times too

http://www.nettletondistrict.com/Nettleton/

**Comment by poblabs** [comment]
I'll have to look to see if it's supported

**Comment by 41south** [comment]
Yeah I was thinking it might need a station time zone in the config or something and then you also have the issue of daylight saving time. But it would seem to make more sense for the graphs to be local to the station rather than the viewer. I guess it depends on whether your expected audience is more local or from further afield. Not so bad here in NZ with just one time zone.

**Comment by poblabs** [comment]
I thought about this on my commute home today and I've tried to take this on previously. You can see some of the history here https://github.com/poblabs/weewx-belchertown/commit/2fef48cff66802588423be6b8bdee3ae79c09281 - basically the [UTC offset is set in the skin](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown_highchartsSearchX.py#L73) and highcharts is supposed to offset by that offset. 

The offset would be relative to UTC but you can see I have `useUTC: false`, and I think that was because of other funky things that happened early on. You can see it here. It's 20:00 for me right now, but the charts are showing into the next day, with the 20:00 in the hover timestamp. 

I might have to do more research on this one. So far I think I'm doing everything the docs and other users say I should be, but the chart remains in the viewers time. 

![image](https://user-images.githubusercontent.com/3484775/50461098-cf7f4d80-0949-11e9-8f0d-376e28d43f39.png)

**Comment by poblabs** [comment]
I finally had some time to sit down, read the documentation and do some tests with this one. Think I've got it. 

[Highcharts uses opposite offset than what is usual](https://api.highcharts.com/highcharts/time.timezoneOffset). 

> Positive values are west, negative values are east of UTC

What I mean is for me in the Eastern timezone, I'm used to be -300 minutes off UTC. However, Highcharts wants that to be 300 minutes offset. It feels backwards and opposite of norm. 

So by taking the moment.js offset of -300, then turning that into a negative (which is -(300), so a positive number), it fixes the issue. 

I created a virtual machine that's in the Sydney timezone and did some test with my site. 

Before:
You can see that midnight station time is 16:00 Sydney time. This is the wrong condition and is confusing to remote viewers.
![image](https://user-images.githubusercontent.com/3484775/52157356-6a133080-265c-11e9-90e0-4ad102726e16.png)

After:
Doing the double negative thing, it makes both timezones show the timeline from the station's midnight. 
![image](https://user-images.githubusercontent.com/3484775/52157368-9333c100-265c-11e9-9881-4b3a0ac456dc.png)

Little more testing to verify and then I think we can close this one.

**Comment by 41south** [comment]
Very cool indeed, nice detective work!

**Comment by poblabs** [comment]
@41south When you get a minute, can you take a look at https://belchertownweather.com/ and see if the charts begin at midnight for you (and not your local 8am?)

**Comment by poblabs** [comment]
Cool, thanks! The "reverse offset" seems to be the trick with Highcharts code.
