### ISSUE TITLE
date/time ranges on highchart graphs and other questions

### ISSUE THREAD

**Issue by gccobservatory** [poblabs/weewx-belchertown#187]
Hello,

I'd like to just first say that I'm thoroughly enjoying the look of the Belchertown skin - it's a stunning skin.  Thanks for all your hard work in developing it.

I have a few questions and if I'm posting in the wrong place or I'm overlooking something that is already been asked elsewhere, or is common knowledge, my apologies.

I'm trying to set the x-axis range on my highcharts graphs to show the entire day, month, year to start at the beginning and end at the end.  For example, on my homepage I've set up the graphs to plot data for today since midnight, but highcharts defaults the x-axis range to show only the data that has already been recorded.  I tried setting xaxis_min=00:00 and xaxis_max=23:59, but that doesn't work.  Likewise, I'd like to show an entire month with the range starting on the first of the month and ending on the last day of the month, regardless if there's data populating the graph.  Ditto for the year.  Is this something that's possible?

Additionally, I've augmented weewx to read data from onewire temperature sensors and have successfully incorporated their data with the highcharts graphs, but I'd like to show current temperatures from these sensors on the homepage.  Here's a snippet of the html code I'm using:

            #if $owTemp0.has_data
            <td style="text-align:center;">$owTemp0</td>
             #else
             <td style="text-align:center; color:red; font-weight:bold;">offline</td>
             #end if

When cheetah runs it doesn't like $owTemp0.has_data and $owTemp0.  Am I missing something?

Thanks in advance for the help!

**Comment by poblabs** [comment]
@gccobservatory Hi, thanks glad you're liking the skin.

To confirm your request, you want to show a chart for the entire week, say Sunday to Saturday. Today is only Monday, so you want a chart to show 2 days of data, and 5 days of emptiness since that timespan hasn't occurred yet? 

If this is my understanding then this won't work. At least not right now. We're only getting the data from the database from data which has already been logged. There's no method in place to create a chart with "data yet to be determined". Highcharts can do it, but this function is not built into Belchertown. 

I'm not sure what this option would be for me to include it. Highcharts requires the timestamp in milliseconds, so I could make something like `xaxis_min = 1563629545000` but that would be a static timestamp. I'd probably have to work on something similar to how `time_length` works, but maybe `xaxis_time_length`? 

`xaxis_time_length = days`, with a partner config for how many units. So if you wanted days, how many days? If you wanted hours, how many hours? etc.

Thinking out loud. Maybe

```
xaxis_time_length = days
xaxis_time_units = 7
```

This would be a constant rolling outlook though. So on every report generation the chart will always show a blank 7 days ahead (in this example). 

In addition I could make a `xaxis_time_length = this_week` or `today`, `this_month`, `this_year`, but this requires research for me to complete for `this_week`. Such as utilizing weewx.conf's `week_start` to figure out when user's week starts. 

Is this what you're looking for?

A quick example: 
![image](https://user-images.githubusercontent.com/3484775/61220917-5c6ed600-a6e5-11e9-8316-be84e48f757c.png)


---

I'd need to see the errors in the syslog for why Cheetah doesn't like `$owTemp0`. This particular item may not be Belchertown related, but I can take a first stab at it to see if it is Belchertown related or not.

**Comment by gccobservatory** [comment]
Yes, that's precisely what I'm looking for.  Is it doable?

And in regards to the Cheetah errors, I figured it out - it was a boneheaded typo.

One other question/request.  Is it possible to include additional bindings in Belchertown other than wx_binding?  For instance, I'm writing a script that takes data from another set of sensors, but I don't want to include the readings in the wx database, but rather create a different one... say like "foo.sdb" and I want to plot the data using highcharts.

**Comment by poblabs** [comment]
Closing this out. This should be available now in 1.1 but if not, surely in 1.2 which is being released soon

**Comment by c0by85** [comment]
Sorry for answering in an closed issue but is that feature available? can't get it to work. want to fix my chart.

![image](https://user-images.githubusercontent.com/25707747/111030633-a866a680-8403-11eb-88b3-ad521e17d3fd.png)
