### ISSUE TITLE
hassio community MQTT addon

### ISSUE THREAD

**Issue by etamtlosz** [poblabs/weewx-belchertown#192]
... and I'm still struggling with this.
I switched to MQTT Server & Web client (Community addon) on my hassio, hoping that I'll be able to keep my data locally, and not sending to some cloud server.

My addon settings look like this:
![2019-08-24 21_12_42-Window](https://user-images.githubusercontent.com/7436784/63635247-b84d5700-c6b4-11e9-8505-50d3007b6a51.png)

My weewx.conf looks like this:
```    [[MQTT]]
        server_url = mqtt://mqtt:pass@192.168.2.10:1883/
        topic = ivcweather
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
```

while my skin.conf contains this:
```    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "192.168.2.10"
    mqtt_websockets_port = 1884
    mqtt_websockets_ssl = 0
    mqtt_websockets_topic = "ivcweather/loop"
```
What am I doing wrong?

**Comment by Stormtracker017** [comment]
In the skin.conf need to add mqtt_websockets_enabled = 1 then restart weewx.

**Comment by etamtlosz** [comment]
It's there. I just used wrongly the back quote in the text editor, that hid the first row of my code.
```
    mqtt_websockets_enabled = 1
    mqtt_websockets_host = "192.168.2.10"
    mqtt_websockets_port = 1884
    mqtt_websockets_ssl = 0
    mqtt_websockets_topic = "ivcweather/loop"
```

**Comment by Stormtracker017** [comment]
I don't know if this is the issue, but try port 9001 for your mqtt_websockets_port.

**Comment by etamtlosz** [comment]
I doubt, but I'll try. Since my websockets ports are 1884 and 4884, it shouldn't work.

LE
Like said, still: Failed connecting to the weather station. Please try again later!

**Comment by poblabs** [comment]
Everything seems correct. Which version of the hassio mqtt addon are you using? I don't use mine for websockets because I didn't have success with it, but I'm on version 4. I noticed a lot of things started to break for me on 4.1 and up. I ended up using my hassio mqtt for a smartthings bridge and then ran my own mqtt broker on the side for weewx and websockets.

Have you tried a [public broker from the readme page](https://github.com/poblabs/weewx-belchertown#mqtt-brokers) to just verify you can get weewx and belchertown working on websockets?

This doesn't seem like a skin issue though.

**Comment by etamtlosz** [comment]
I'm using the community addon (based on hivemqtt), maintained by Frenck. https://github.com/hassio-addons/addon-mqtt
Until last week I've used an externally hosted mqtt broker - hivemq.com - and it was working.
I'm trying to switch to the hassio broker, so I can have my weather data in home assistant.

**Comment by poblabs** [comment]
Yes, I'm using the same one. I didn't have good results which is why I moved on from it. Yes, I run 2 brokers, one in hassio and one for weewx. 

Some things to check: 

* Check docker to make sure the ports are mapped to the container correctly. 
* Check your firewall to make sure the ports are open.
* Try the [mosquitto_sub utility](https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/) to make sure that weewx data is being received onto the broker from weewx. If you can see data being published, then it's a websockets problem. If you don't see data being published then you have a bad config with weewx or the ports aren't available for weewx to be able to publish data to. 
* Try a [websockets test utility](https://hobbyquaker.github.io/mqtt-admin/) to see if websockets are working on the broker. If not, maybe Frenck can help you. 

Perhaps @the-butterfry can jump in too. They had mentioned [they use hassio](https://github.com/poblabs/weewx-belchertown/issues/150#issuecomment-497964464) previously as well. 

Since this was working on a public broker previously I'm going to close this since it's not a skin problem. But feel free to keep collaborating if needed

**Comment by poblabs** [comment]
Actually, looks like I might be using a different addon for MQTT. https://www.home-assistant.io/addons/mosquitto/

Does your addon have the hivemq dashboard right in hassio? If so, do you see weewx data?

**Comment by etamtlosz** [comment]
- Ports seems to be mapped correctly, according to portainer:
![2019-08-26 08_22_34-Portainer](https://user-images.githubusercontent.com/7436784/63655316-bf6e8500-c7da-11e9-85cd-965ac449691d.png)
- Ports are open
- broker is receiving data, I'm using MQTT explorer to verify this
![2019-08-26 08_24_28-MQTT Explorer](https://user-images.githubusercontent.com/7436784/63655335-f5ac0480-c7da-11e9-91ea-5dbc42363769.png)

The publishing looks OK in the log, as well:
```
1566765452: New connection from 192.168.2.61 on port 1883.
1566765452: New client connected from 192.168.2.61 as auto-0DE47435-DCE9-2E40-5ED6-FDF340506B48 (p2, c1, k60, u'mqtt').
1566765452: No will message specified.
1566765452: Sending CONNACK to auto-0DE47435-DCE9-2E40-5ED6-FDF340506B48 (0, 0)
1566765452: Received PUBLISH from auto-0DE47435-DCE9-2E40-5ED6-FDF340506B48 (d0, q0, r0, m0, 'ivcweather/loop', ... (717 bytes))
1566765452: Sending PUBLISH to auto-93FF42E8-E884-048E-9950-73281E051C5C (d0, q0, r0, m0, 'ivcweather/loop', ... (717 bytes))
1566765452: Sending PUBLISH to mqtt-explorer-65fe0990 (d0, q0, r0, m0, 'ivcweather/loop', ... (717 bytes))
1566765452: Received DISCONNECT from auto-0DE47435-DCE9-2E40-5ED6-FDF340506B48
1566765452: Client auto-0DE47435-DCE9-2E40-5ED6-FDF340506B48 disconnected.
```
192.168.2.61 being the IP of my weewx.

When I'm opening the weewx webpage I see an error in the log, :
```
1566765452: Sending CONNACK to 192.168.2.204 (0, 5)
1566765452: Socket error on client <unknown>, disconnecting.
1566765452: Sending CONNACK to 192.168.2.204 (0, 5)
1566765452: Socket error on client <unknown>, disconnecting.
```
192.168.2.204 is the IP of my desktop.

Yes, the addon does have the hivemq dashboard, an I can see the weewx data.

**Comment by poblabs** [comment]
Is your website public and your broker public? Or are you accessing this only on a LAN?

**Comment by etamtlosz** [comment]
It is public, http://ivcwx.duckdns.org:9812

**Comment by poblabs** [comment]
Do you have a port forward for your MQTT broker? I'm not able to access it from your duckdns

**Comment by etamtlosz** [comment]
I had the wrong ports opened in my router.
Now I have the correct ports opened, 
As you can see, I can connect to my ws port (1884), and can see the data with hobbyquaker.github.io/mqtt-admin 
![2019-08-26 20_54_26-Window](https://user-images.githubusercontent.com/7436784/63678718-e01ef500-c843-11e9-9566-9f4f53a362a8.png)

I even tried to switch my mqtt_websockets_host from "192.168.2.10" to "ivcwx.duckdns.org"

**Comment by poblabs** [comment]
Ok, I think we're onto something here. 

I can't connect to your broker at all. I'm not authorized. 

> weewxlab:~$ mosquitto_sub -h ivcwx.duckdns.org -p 1883 -t ivcweather/loop
>Connection Refused: not authorised.

It's best for MQTT and Websockets to allow anonymous users because me, for example, have no way to authenticate through your website. To authenticate you would have to hard code that into the source code - but then that defeats the purpose of authentication if it's in plain text and easy to find. 

[If you take a look at my MQTT tutorial](https://obrienlabs.net/how-to-setup-your-own-mqtt-broker/), you'll see I apply an ACL to the anonymous user to only be able to read the SYS and the weather topics. They cannot publish updates or subscribe to anything else. 

I say set `allow_anonymous` to true in your MQTT config, restart the MQTT server and see what happens. 

It doesn't look like you get the fine-grain control that's in my tutorial though, so your mileage may vary. 

I suspect the blocked anonymous access is the problem here. 


![image](https://user-images.githubusercontent.com/3484775/63902440-a8e14d00-c9d7-11e9-8176-d47bd40b0ff8.png)

**Comment by etamtlosz** [comment]
I've just set "allow_anonymous": true and now it's working. Thanks
I don't like the anonymous way, but if that's the only one, I have to live with it.

**Comment by poblabs** [comment]
It's one way. You'll have to research if anonymous can publish. If so then
you'll want to evaluate that risk and live with it or run a separate broker
or use a public one.

Glad this one is resolved.
