### ISSUE TITLE
Wrong Temperature when accessing webpage

### ISSUE THREAD

**Issue by ebnerjoh** [poblabs/weewx-belchertown#220]
Hi,

I noticed the follwoing on my MQTT enabled setup:

When accessing the webpage the first time, it shows me "last updated" a couple of minutes ago, but the main temperature is from a couple of hours ago. Only after the next MQTT update I can see the correct temperature.

Best Regards,
Johannes

**Comment by poblabs** [comment]
Whats the URL to your site? Which version are you using? The skin grabs the initial page load data from your database using $current.outTemp. So to say the skin is just showing your database latest values.

**Comment by ebnerjoh** [comment]
wetter.familie-ebner.at

something is then wrong. because there are newer entries in the database. If I scroll down the page to check the graph, I can see the latest temperature. 
Only the main Temp display shows an older entry for about 1 minute (until MQTT is updating it).

Br.
Johannes

**Comment by poblabs** [comment]
Your site isn't loading for me. What version of the skin are you using?

**Comment by ebnerjoh** [comment]
Can you try again?

I am using 1.1b8.

This is the temperature I saw just now (05:30 in the morning) when accessing the site:
![image](https://user-images.githubusercontent.com/46743596/67652805-e5351900-f946-11e9-99db-7d9d7c136289.png)

This is the Graph for the Temperature:
![image](https://user-images.githubusercontent.com/46743596/67652816-fda53380-f946-11e9-8861-cd52ad05df64.png)


And this again the main temp after the first mqtt update:
![image](https://user-images.githubusercontent.com/46743596/67652833-0f86d680-f947-11e9-9e49-47eb21d07f29.png)

Br,
Johannes

**Comment by poblabs** [comment]
I'm seeing this now with my own site. I'm not sure why it's doing this yet but I'm looking into it.

**Comment by poblabs** [comment]
Ok my issue was identical to your issue but it was a database problem; not a skin problem. 

I am suspecting you have something similar wrong. What do you see in your syslog?

**Comment by ebnerjoh** [comment]
I was checking the logs and didnt find any issues. But I noticed something different. It is not related to the skin but to weewx.

I am running weewx on a RPi Zero with an archive interval of 15 Minutes. When the archive process is running, then there is a python process using 100% CPU and the load goes up to 1. 
Thi s process is running nearly 13 Minutes and then disapears. Load and CPU is going down for ~1 minute and the next process is starting.

I also noticed that the issue with missing "main Weather Image" exactly happens when I refresh the page ~1 Minute after the archive process starts. Again 1 Minute later I can see it again.

**Comment by poblabs** [comment]
Your Pi may not be strong enough to run the skin? If you disable the skin in weewx.conf, does it help your Pi load averages?

**Comment by biltmorelaker** [comment]
My RPi Zero W is running with an archive interval of 5 minute. Archiving does pin the CPU at 100%, but it only lasts for about 1 minute and 20 seconds or so and then CPU drops to 25%.  If I refresh my web page ([https://wx.kutzenco.com](url)) while cpu is at 100% it shows the latest archive value for temp which updates as soon as the MQTT value is received (within a second or two). The same thing happens if I refresh between archive intervals when cpu is in the 25% range or so. 

So, I am not seeing the behavior described by @ebnerjoh with my setup.

**Comment by biltmorelaker** [comment]
I should point out that I am running a Davis Vantage Vue weather station with a Belfryboy USB logger sending data from the Davis console to the Pi Zero W.

**Comment by poblabs** [comment]
I'm not quite sure where to go with this one. If it's taking this long to process the skin, then it could be an issue with the "horse power" the Pi has (or lack of), and maybe the size of your database, etc. 

You could try to upgrade to [1.1 beta](https://github.com/poblabs/weewx-belchertown/tree/development), and use the new [`generate`](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#generate) feature which allows you to generate charts at specific intervals. 

For example if your Year chart is killing your Pi because of the amount of database queries, then you can set to generate that graph group only once a day. That alone would speed up chart generation when they are on the regular intervals since it would skip the year chart.

**Comment by ebnerjoh** [comment]
Hi, 

Yes, I also think it is not skin related. I will try the "generate" feature and if that is not working I will try a normal Pi instead the Zero.

Br,
Johannes

**Comment by ebnerjoh** [comment]
A first test looks very good. The Utilization is now much lower and it seems that the page is always up2date.

I will continue monitoring
