### ISSUE TITLE
Feature request: Ability to choose either visibility or cloud base/height

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#24]
Hopefully just a simple skin.conf setting, the ability to choose one or the other of visibility (from Darksky?) or cloud base as transmitted or derived by most weather stations. Possibly add a calculation to derive it from temp and dewpoint if it isn't already in the users data?

Cheers
Colin

**Comment by poblabs** [comment]
Looks like [weewx can calculate cloud base within weewx core](https://groups.google.com/d/msg/weewx-user/PCoEe1ojak4/NFlkNBJ7AwAJ) as long as you extend the database. So this is an option, but not one out of the box - which may be confusing for average users on how to enable this feature. 

I'm not sure if I can [tap into the weewx calculations](https://github.com/weewx/weewx/blob/e4693b025d80196a7c25ef0f015045f53aa8c248/bin/weewx/wxformulas.py#L360-L389) within the bin/user/belchertown.py file since I don't think I can get loop data during report time. 

Which leaves me the option to calculate it within the skin itself which might not be ideal because of the unit conversions (foot and meter). 

I need to think about the best way to do it

**Comment by poblabs** [comment]
I suppose I could just add an option to enable cloudbase instead of visibility and have it included much like appTemp?

**Comment by poblabs** [comment]
I think I will go that route. 

Treat it like a user-controller option after extending the database. I even wrote a [Belchertown skin wiki on how to do the database extensions](https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database) since it seems more people are interested in the additional observations (appTemp specifically). 

I'll do some testing and will push a commit you can test with. It will require a skin.conf upgrade.

**Comment by poblabs** [comment]
Take a look at https://github.com/poblabs/weewx-belchertown/commit/41b1fa7a297b44bd77ceb5af01420c8fb20453fb. Download the new styles.css, index.html.tmpl and skin.conf. Then add new skin option `show_cloudbase = 1` to your skin options and restart weewx.

It should look something like this. I've kept visibility in there too since they are two different observations. 

![image](https://user-images.githubusercontent.com/3484775/50490850-53cee080-09dd-11e9-9ee6-3a04088baaa2.png)

**Comment by 41south** [comment]
Looks like we have to old metric/imperial clash again. My extra section shows the correct height where as the new section you've added looks to be the metric equivalent with 'feet' after it. In the attached the 2900 feet is correct
![screen shot 2018-12-31 at 4 04 55 pm](https://user-images.githubusercontent.com/1725001/50553938-4899ee80-0d16-11e9-8855-504172f5eb24.png)
![screen shot 2018-12-31 at 4 05 21 pm](https://user-images.githubusercontent.com/1725001/50553939-4899ee80-0d16-11e9-9152-6e2e4f06f821.png)

**Comment by poblabs** [comment]
What is your mqtt extension sending units set as?

**Comment by 41south** [comment]
[[MQTT]]
        #This section is for the MQTT service setup
        server_url = mqtt://192.168.20.121:1883/
        topic = weather/41south
        unit_system = METRIC
        binding = loop
        aggregation = aggregate
        log_success = False
        log_failure = True
        [[[inputs]]]
            [[[[dayRain]]]]
                name = dayRain_mm
                units = mm
            [[[[rainRate]]]]
                name = rainRate_mm_per_hour
                units = mm_per_hour

**Comment by poblabs** [comment]
I think you can override it similarly to how you've done the others.
Observation is "cloudbase" then define your unit and restart weewx.

**Comment by 41south** [comment]
So ...
[[[[cloudbase]]]]
name = cloudbase_feet
units = feet

I noticed that the correct value is there after a screen refresh before the MQTT data kicks in

**Comment by 41south** [comment]
Close :)

[[[[cloudbase]]]]
name = cloudbase_foot
units = foot

Fixed - thanks.

Can be closed I think.

**Comment by poblabs** [comment]
Great!
