### ISSUE TITLE
Weather Warnings.

### ISSUE THREAD

**Issue by ijg** [poblabs/weewx-belchertown#244]
Hello,

First of all, incredible skin.  I'm having a ton of fun customizing it.

Are weather warnings/alerts etc saved in a database?  It seems each time environment Canada 'updates' the time on the severe snowfall alert for our area for example, another line is added to the top of the page.  Yet if I check the rss feed, they only list 1.  (They just keep re-releasing it.)

Snowfall Warning in effect until January 18, 2020 8:04 PM
 Snowfall Warning in effect until January 18, 2020 8:04 PM
 Snowfall Warning in effect until January 19, 2020 12:11 AM
 Snowfall Warning in effect until January 19, 2020 2:52 AM
 Snowfall Warning in effect until January 19, 2020 4:12 AM
 Snowfall Warning in effect until January 19, 2020 7:57 AM
 Snowfall Warning in effect until January 19, 2020 10:31 AM

https://weather.gc.ca/rss/battleboard/on61_e.xml

Is it possible to either 'limit' the number of alerts that are shown at any one time?  I guess you possibly don't get your feed right from the government, so maybe it's Dark Sky that's causing this?

Thanks for your help.

ig.

**Comment by poblabs** [comment]
Thanks, glad you like the skin. The weather warnings come from DarkSky. This particular issue is often reported to me, but the skin "shows what DarkSky tells it to show". I have no idea why DarkSky has multiple alerts for the same thing. If you click on each alert you will notice they are all unique. This prevents me from showing a limit because they're unique. It could be geographic or otherwise something else that makes DarkSky give all the alerts for your lat/lon.. You could reach out to them through your developer portal and ask them why they show so many alerts?
