### ISSUE TITLE
Feature request: turn on/off Wind Chill and heat Index

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#25]
Just thinking aloud a little on this one, triggered by your addition of appTemp to the chart (which is great!). I'm not sure how many sites I've seen where Wind Chill and Heat Index are used or displayed. They seem to be the same as Temp most of the time and are displayed whether or not they are used. Perhaps a skin.conf setting to turn those on and off - as per appTemp?

**Comment by poblabs** [comment]
Hah interesting thought. I'm sure you can see - based off my commits - on whether or not to include appTemp in the charts. 

Maybe I make appTemp, heat index and wind chill all optional on the temperature graph? 

I worry about too many options confusing people but I'm struggling with this one :)

**Comment by 41south** [comment]
That is true regarding the too many configuration items. As I say just thinking out loud and perhaps it might make the graph a little cleaner when you hover - but definitely not a big one. Feel free to close it off as a maybe :)

**Comment by poblabs** [comment]
Too many options might be ok as long as they are self-explanatory like `highcharts_show_apptemp` or `highcharts_show_windchill`?

**Comment by 41south** [comment]
Yeah absolutely. I kind of figure that the sort of person dabbling in Weewx and skins will have a reasonable knowledge to handle configuration items. I could be wrong and certainly don't want to make more support work for you (than my suggestions already do!) What are your thoughts on the usefulness of this?

**Comment by poblabs** [comment]
Well I don't think it'll be much work to make it an option on the charts, really. I was already teetering on just not including appTemp all together - so I could just make it an option and have the user decide if they want all 3 or not (or a combo of)

**Comment by poblabs** [comment]
One thing that'll need to be tested is if I disable windchill but enable heatindex, will it show? I wonder if JavaScript will get finicky about this.

**Comment by poblabs** [comment]
Yep - it'll fail if all the sequences aren't enabled because of their numbered order. I think I know a fix. I'll have to issue an update on it.

**Comment by poblabs** [comment]
After **a lot of trial and error**, I committed https://github.com/poblabs/weewx-belchertown/commit/50bc633b02bec32a31ba7ad6f46717b8ab10c271 which seems to be working no matter what you have on or off for that chart. 

Give it a thorough test please? :)

**Comment by biltmorelaker** [comment]
We should be clear about the relationship among Temperature, Wind Chill, Heat Index and Apparent Temperature.

1. When the Temperature is 50 degrees F or below the Wind Chill describes what the temperature feels like due to the effect of wind. It is always less than or equal to the Temperature.

2. When the Temperature is 81 degrees F or above, the Heat Index describes what the temperature feels like due to the effect of humidity. It is always greater than or equal to the Temperature.

3. The Apparent Temperature is equal to the Wind Chill when the Temperature is 50 degrees F or below; equal to the Temperature when the Temperature is between 51 and 80 degrees F; equal to the Heat Index when the Temperature is above 81 degrees F.

This is why when you overlay the lines on a graph, you don't always see multiple lines since they overlap. Many individuals won't want all of these enabled. I personally like plots to show Wind Chill, Temperature and Heat Index overlayed and not show Apparent Temperature. But for an current readout, I like to see Apparent Temperature as a "Feels Like" number in addition to Temperature.

That said, I agree with Pat that choice is great as long as it doesn't confuse people. Flexibility has great value. Pat's done a terrific job! I'll test the new commit as well.

**Comment by poblabs** [comment]
Closing this one since it went out in 0.8 :)

**Comment by 41south** [comment]
Yep, works great, thanks
