### ISSUE TITLE
Feature Req : Select time to show values

### ISSUE THREAD

**Issue by Drealine** [poblabs/weewx-belchertown#274]
Hi @poblabs 

I would like to ask if it possible in the futur to make a column for select the date to show value in HighCharts like Graphics & records. 
Some people who comes on my website tell me if it possible ahah.
Also, I saw in HighCharts that I can set a Windbarb like this : https://www.highcharts.com/demo/windbarb-series I think is not an issue but a feature ? Because when I've set the type, is not showing on my website.

I can help you if it possible. I've some basics on python.

**Comment by magnum61** [comment]
I have installed Belchertown skins recently, all is working. The skin is the most complete i've seen so far

But I also would like to have a Date picker implemented for the graphs. Sometimes it's required to to back one or two days.
It does not help to check the weekly or monthly and zoom in, because it does not give the level of detail 

Unfortunately my coding skills are not sufficient to do it on my own

**Comment by poblabs** [comment]
@magnum61 We are unable to do that because of the way weewx works. Every archive interval the graphs.conf exports a JSON file specific to what you want. To be able to have access to everything, we would need to export **everything** in your database every 5 minutes. For users on a raspberry pi, or for those with large databases, this is unfeasable. Sorry!

**Comment by magnum61** [comment]
OK, thanks for explaining the situation
