### ISSUE TITLE
Feature request: Only use Darksky 'current conditions' icon

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#29]
I've found the Darksky forecast to be quite inaccurate down in this part of the world so have gone to using the local Metservice widget. This however removes the current conditions icon near the temp - which strangely was always quite accurate.
I think reading the forum others would also like some flexibility in the forecast data but would like to retain the current conditions icon.

Is it possible to retain the current conditions icon regardless of whether or not the forecast is displayed?

**Comment by poblabs** [comment]
Since the icon comes from darksky, but you don't want the darksky forecast row, no they are both linked right now. 

You could just hide the darksky forecast row with some CSS though. 

[In the skins/Belchertown/style.css file, at this area](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/style.css#L1835-L1837) for `.forecastrow`, add a `display: none;` beneath the text-align. Restart weewx and see if it goes away.

**Comment by 41south** [comment]
You are the master! That works perfectly, thanks. If I can find who else was asking about that I'll let them know. I guess style.css will be overwritten with updates?

**Comment by poblabs** [comment]
Yeah it will overwrite on upgrades and nope the syntax doesn't matter. Closing for now since this seems to be a one-off and is an easy personal fix on upgrades.
