### ISSUE TITLE
Layout on iPads with 1024px width

### ISSUE THREAD

**Issue by James-76** [poblabs/weewx-belchertown#316]
Can anybody with good CSS skills work out how to improve the layout so windrow stays under temperature?

![image](https://user-images.githubusercontent.com/59254774/85920189-8a531900-b869-11ea-808a-3296d602c2f6.jpeg)

I'm getting the same if I set Firefox to emulate being 1024px width so I'm guessing you can change it somehow in the iPad Landscape section in style.css

James

**Comment by poblabs** [comment]
I don't have an iPad but I can work on this. Might need a new media section in style.css. It's definitely 1024px width?

**Comment by James-76** [comment]
It appears to be.   The screen capture was from my iPad, and if I use the Responsive Design Mode in Firefox and set to 1024 x 768 it looks the same.

![web](https://user-images.githubusercontent.com/59254774/85928920-ab872a00-b8a8-11ea-9c14-aaa544c7a471.png)

There is also an iPad section in your style.css which if I play around with does make changes to what I see.

I must admit the iPad specification says it is 2048x1536px it appears to be displaying in Safari in 1024x768.

**Comment by poblabs** [comment]
On quick effort the closest I can get with the current row "grid" CSS system is the below. It's still a little ugly. 

It might be beneficial for me to research switching from the grid to the flexbox style of CSS since I think that can be a little more flexible. This will probably take weeks of time though - I might release 1.2 first then maybe that's a feature of 1.3?

I'll keep playing with this layout though to see if I can find the right mix of floats. 

![image](https://user-images.githubusercontent.com/3484775/85935082-62d86c80-b8ba-11ea-8495-a3ebf87885c1.png)

**Comment by poblabs** [comment]
Or if you want something a little more basic like the below, then just delete the whole section from style.css and wait for an archive period. 

Delete this section: 
```
/* iPad Landscape */
@media only screen and (min-device-width : 768px) and (max-device-width : 1024px) and (orientation : landscape) {
```

---

![image](https://user-images.githubusercontent.com/3484775/85935418-9ddc9f00-b8be-11ea-85e2-ca6c3be75636.png)

**Comment by James-76** [comment]
Yes.

I was just seeing if we can get the layout cleaner looking for smaller screens.

As you say possibly one for 1.3

What did you change for the first layout attempt?

James
