### ISSUE TITLE
Adding Gas Measurements to charts? And how to add additional temp values to graph?

### ISSUE THREAD

**Issue by earlthesquirrel** [poblabs/weewx-belchertown#320]
Hello,

I'm on day 3 of weewx (so far have everything installed and using WeeWX-MQTTSubscribe  I've got data feeding in from the  various sensors around the house.   I have your skin installed and have been learning how to add charts.   THANKS so much for it (and all the work you've obviously put into it)

Two questions:

1) You don't seem to have any gas measurements charted/displayed.  I would like to add a section of charts that were gas measurements (at least to me, air quality goes with weather....)   Do you have any pointers/suggestions for a section of charts that show the various gas measurements that Weewx can collect?  (I just posted a question to the weewx development site about additional gas measurements I can currently collect.... so I'd have additional measures as well)

2) I also have multiple temperature values being collected.  I was trying to update the graph to show both of them.  That was fairly trivial to do.  However, the windchill, heat index and dew point confused me.  If I'm tracking two temps are the two sets of these values?   Are they only available based on the outTemp value?  Or?

**Comment by bellrichm** [comment]
Earl,
Glad you are finding it useful.  Half the fun is finding out how different people are using it!
These questions are beyond my WeeWX knowledge and I think you will get some good info from your questions on the WeeWX forums.  I’ll pipe in from the MQTTSubscribe side of things as needed over there.

It does sound like reading http://weewx.com/docs/customizing.htm is the place to start.
rich

**Comment by bellrichm** [comment]
Eral, woops thought I was on MQTTSubscribe. Please ignore last comment

**Comment by poblabs** [comment]
Gas measurements aren't part of weewx's core, they typically require and extension. If you're using an extension you should be able to graph those measurements. I think most of them save measurements to a separate database, so for the graph group you would define that [database binding](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation#data_binding), then graph the column name within that database. 

Your 2nd question confuses me a little bit. The graphs will graph anything in the database and the observations are the column names within the database. So `outTemp`, `dewpoint`, `windchill`, etc., those are calculated by weewx itself, saved to the database, then Belchertown graphs it if you'd like. Does this help?

[The Belchertown charts wiki is full of information](https://github.com/poblabs/weewx-belchertown/wiki/Belchertown-Charts-Documentation). It's long and detailed. but I think it covers everything you need.

**Comment by earlthesquirrel** [comment]
Regarding the two questions:

1) The existing DB from weewx contains CO2, NH3, NO2, O3 PB (lead) pm10_0, pm1_0 pm2_5 and SO2 as columns.  So it seems that weewx does support gathering some pollution gases.   I'll have to go thru the chart pages further to see how to build a "Air Quality" graphs utilizing your skin.  The graphing document has been VERY helpful, just was wondering if anybody had asked before... (I've had mixed results in the past trying to visualize the numbers... some scales work together, but I don't have good ranges for the various gases to know for sure)

2) In the graphs.conf I added:

[[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
       [[[extraTemp1]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
            color = "#f7a35c"
        [[[dewpoint]]]
            color = purple

The question was with 2 temperature measurements (which don't always give same value) windchill, heatindex and dewpoint would only reflect one of the two temps.  I didn't see reference to a windchill1, etc.    I did see a dewpoint1. and a heatindex1.  Does extraTemp1 and extraHumid1 line up to those two values?   I'm just trying to see what makes sense to keep on the graph... and what makes sense.  Two graphs with 2 sets of measurements, a graph with just temps, etc.
Does it make more sense now?

**Comment by poblabs** [comment]
1. Ah yes. weewx just added these fields to the schema with version 4 - so only maybe a month or so old. I think the idea is for extensions to save to the main database instead of maintaining multiple bindings and/or planning for the future of weather stations which may have this data build into their loops. Right now your driver or extension needs to calculate and save these values from your sensor. For information on this your best bet is the user forums. Once you get those columns populated with data, you can use the column names to chart those values. 

2. This sounds more like a weewx question than a Belchertown question. weewx is the one doing those calculations and again the user forums may have more information for you (someone with better knowledge can probably answer how they're calculated). Typically the extraTemp1, dewpoint1, heatindex1, etc. are just extra fields in case they're needed for extensions, loop data, etc. Same as item 1, the charts will graph the data within the columns, so once you know which one you want to show just include it in the triple brackets and you should be good to go.

**Comment by 41south** [comment]
I get my gases data in using filepile (I've been doing it since quite a way
before the native Weewx support kicked in) and then display it in my
Belchertown charts here.

http://41south.nz/graphs/?graph=AQM

It's fairly basic and, like the rest of the site, is still a work in
progress :)

[AQM]

        show_button = true

        button_text = AQM

        time_length = today

        [[chart1]]

          title = Air Quality Data CO2

          [[[AQICO2]]]

                name = CO2 level (Inside)

                [[[[numberFormat]]]]

                decimals = 0

                decimalPoint = "."

                thousandsSep = ""

        [[chart2]]

          title = Air Quality Index

           [[[AQIIndex]]]

                name = Air Quality Index

                [[[[numberFormat]]]]

                decimals = 0

        [[chart3]]

          title = Dust Concentration

          yAxis_label = "Dust Concentration"

          yAxis_label_unit = "ug/m3"

            [[[AQI25]]]

                name = PM 2.5

                [[[[numberFormat]]]]

                decimals = 1

            [[[AQI100]]]

                name = PM 10

                [[[[numberFormat]]]]

                decimals = 1

Colin

**Comment by earlthesquirrel** [comment]
Thanks, after some playing I have a new "Air Quality" button with the relevant graphs.
