### ISSUE TITLE
radar_html option refresh weather radar image javascript code

### ISSUE THREAD

**Issue by sgrayban** [poblabs/weewx-belchertown#33]
So for the past 2 days I added some js code to auto refresh my radar image source. This is what I came up with, maybe you might want to add it as it wont affect the website if you DON'T use the radar_html.

In **header.html.tmpl** I added
```
<script language="JavaScript"><!--
function refreshIt() {
   if (!document.images) return;
   document.images['myRadar'].src = 'http://radar.weather.gov/lite/N0R/OTX_loop.gif?' + Math.random();
   setTimeout('refreshIt()',300000); // refresh every 15 minutes
}
//-->
</script>
```
before the <**/head**>

Then in the same file I added to the end of the <**body**> tag this...
` onLoad=" setTimeout('refreshIt()',5000)"`

Then for the **radar_html** I use.......

`radar_html = "<img src='http://radar.weather.gov/lite/N0R/OTX_loop.gif' name='myRadar'>"`

I think it's worth to add if someone is using the radar_html option. Like I said it doesn't hurt the site if **radar_html** isn't used.

Thoughts Pat ?

**Comment by poblabs** [comment]
This is a good catch and I have a few thoughts. I think so far everyone who is using the skin is using windy, so I hadn't considered an img refresh. 

Looking at your code:

If I'm reading it correctly, it'll only refresh images in the "myRadar" container? Where is this? The div for the radar is `.radar-map`, so wouldn't you want to trigger on that?

Why the `if (!document.images) return;` section? The document will almost always have images due to the forecasting icons, and other images like a logo, etc. Is this necessary?

Your code comment says refresh every 15 minutes but you have it set for every 5.

Last thought: since this will only affect the home page, there's no sense it placing it in the header. You can instead place the function [before the MQTT section](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L180) in `index.html.tmpl` and setup the timeout for image refresh from the [`jQuery(document).ready(function()`](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L19) (the image will be loaded automatically upon initial page load since it's a standard `img src` - no need to refresh from the document ready).

I may take this idea and implement it though but to be more inline with the skin. For example non-MQTT pages do not have background refreshing so it's not needed. If the user is using MQTT then they get the benefit of background refreshing. So in that case I'd maybe refresh the div entirely on archive interval - much like [how the forecast data and chart data is reloaded automatically on archive](https://github.com/poblabs/weewx-belchertown/blob/master/skins/Belchertown/index.html.tmpl#L477).

Some good thoughts here though! Will have to do some testing so I can get it in for the next release.

**Comment by sgrayban** [comment]
I just copied it from another site I have that using this code.....

`if (!document.images) return;`

Isn't needed but just copied it anyway. You can remove that.

In weewx.conf in the option radar_html I use.......

radar_html = "<img src='http://radar.weather.gov/lite/N0R/OTX_loop.gif' **name**='_myRadar_'>"

The **name** _myRadar_ is what the JS is looking for. I don't know of any other way to add this.
