### ISSUE TITLE
Feature request - add web page extensibility to allow customised pages to be added

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#4]
So my thinking here is along these lines;

I would like to add a couple of extra web pages to the site. One for my local lightning data from Blitortung.org (I have a station here) and the other is for Air Quality Data using graphs generated at ThingSpeak which can be "iframed" into a page. My thoughts would be pages along the lines of the 'about' page where a user could add text, html or iframes etc using an '.inc' file. Some way to add the page links to the top of each page would be required - but this could may be be along the lines of adding page tiles to a conf file and then the user creating an associated folder and then adding the inc file. The extra pages would take their style from the rest of the skin.

Possible?

**Comment by poblabs** [comment]
I saw your comment flash by in the barrage of other comments from that thread and have been thinking about it on and off the last few days. 

The `install.py` file shouldn't touch anything it's not aware of. So if you made a folder called `lightning` and inside added an `index.html.tmpl`, you could copy everything from the About page's `tmpl` file, and copy it there. Upon upgrades the files should remain untouched since the installer isn't aware of them. 

This is good and bad. 

Good because your custom page won't be touched. 

Bad because the lightning's index.html.tmpl file needs to be in skin.conf (mirrored after the about page), and the nav menu is in header.html.tmpl, so if you add the page to these 2 files, they'll get overwritten on upgrades. 

I'm sure that there are ways to expand the template generator to be more dynamic, but I'm not familiar with them.

**Comment by mash55** [comment]
I second this request... in addition to lightning and airquality data, weather cams, timelaspe video come to mind...

**Comment by poblabs** [comment]
Have a user add a custom page themselves can totally be done. Either by hand in the /var/www/html dir or as part of the /etc/weewx/skin method. The problem you run into is the page being deleted potentially on upgrades. 

This is slightly out of my scope right now (so many emails to resond to with users having other issues :) but maybe a write up on the readme could be a good starting point?

**Comment by sgrayban** [comment]
This is doable unless you have done this step to reduce r/w on the sdcard
https://github.com/weewx/weewx/wiki/Minimize-writes-on-SD-cards

Which I did.

**Comment by poblabs** [comment]
@sgrayban How does that apply to this issue?

**Comment by poblabs** [comment]
To everyone else, I'm not sure I can programatically implement something like this. The user would have to customize it to their own site that they want. Maybe a wiki outlining the steps it would take to add new pages and their content would solve this issue?

**Comment by sgrayban** [comment]
It applies because the html reports are written to a tmpfs. If the user uses this and stores static pages it will be delete when the pi is rebooted.

weewx_html      /home/weewx/public_html tmpfs   size=20M,noexec,nosuid,nodev    0       0

**Comment by 41south** [comment]
Yeah I was going to close this given what you've added for the extra sections. The instructions you gave me a while back work perfectly, it just needs to be redone after after an update but I don't think it's too onerous a job, I'd be happy to do a how-to if you like, seeing as how I've had it working

**Comment by poblabs** [comment]
Ok, that's probably more a general tip than this issue which is related to having the ability to customize and add new pages.

**Comment by poblabs** [comment]
@41south Works for me if you want! Close this issue if/when you're happy. Thanks!

**Comment by poblabs** [comment]
Closing this issue

**Comment by ZXant** [comment]
Pat

I was thinking of an extra page as well. I truly appreciate the capability of "page inserts (xxx.inc)" on Homepage, and played a bit with radar maps and external widgets. It works great, but also in respect to Belchertown modern elegance and cleanness, don't want to overload.

That said, I've been considering a "Forecast" page on Menu, leaving homepage mainly for PWS measurements, while still providing further forecast graphs and widgets in separate page.

Its mentioned on this forum, that some instructions to manually patch for an extra Menu page was previously provided (but could not locate). Can please point-out.

Obviously, this is not a major issue, and pending your time availability and priorities.

Thanks,
Xant

**Comment by poblabs** [comment]
This is a very much requested feature and the reason it hasn't been included as part of the base code is because of the way weewx works with the Cheetah HTML generator. Right now it has to be a 100% custom solution that cannot be supported by the skin. 

Custom meaning, add the new folder, add your new files, add it to the nav menu, then add to skin.conf. 

Right now there's no skin option that can automate any part of that - especially adding to skin.conf. 

If anything, it's worth documenting how it's done, but that's about it.

**Comment by ZXant** [comment]
Acknowledged. I tweaked a little, and think starting to figure out. Thanks.

**Comment by ZXant** [comment]
```

My notes, to manually adding new page to Belchertown skin Menu:


1) Skin.conf
- # Navigation Menu, add:
nav_'newPage' = 'newPage'
- # Default page headers, add:
'newPage'_page_header = " 'newPage header' "
- CheetahGenerator section, add:
[CheetahGenerator]
   [[ToDate]]
     [[['newPage']]]
        template = 'newPageFolder'/index.html.tmpl

2) header.html.tmpl
Under <section id="nav_menu">, add new <li class="menu-item menu-item-#'>, 
reordering menu-items in desired order; 
for example, 'newPage' as 2nd menu-item after Home, add:

<li class="menu-item menu-item-1">
<a href="$relative_url/'newPageFolder'" itemprop="url">
<span itemprop="name">$obs.label.nav_'newPage'</span></a></li>

reordering following menu-items: 2,3,4,5

3) page-header.inc
Add after #if $page == "graphs" <h1>...</h1>:

#else if $page == "'newPage'"
   <h1>$obs.label.'newPage'_page_header</h1>

4) New Folder
Create folder 'newPageFolder'
Copy 'about.inc.example' into 'newPageFolder', and edit accordingly
```

**Comment by greenembrace** [comment]
@ZXant, thanks for details that. it works a treat.

**Comment by ZXant** [comment]
@greenembrace, thank you for note, and glad you found (it has been a while...)

Here is my PSW-site with 2 extra pages on Belchertown skin (Forecast, Grafana): http://appnea.net/

Xant
