### ISSUE TITLE
Wind direction in forecast

### ISSUE THREAD

**Issue by NickB1** [poblabs/weewx-belchertown#477]
Hi,

Is it be possible to add the wind direction to the forecast in any way?

Thanks for providing this great skin!

Nick

**Comment by michaelundwd** [comment]
I'm replying rather as I have done a lot of work on the PR for the 1hr and 3hr forecast.  A couple of practical problems.
1) The wind direction data provided by the Aeris forecast api contains the following of which the first one (see below) is ok for the 1hr and possibly 3hr forecasts, but because the wind direction can change significantly in a 24hr period, I'm not sure what value that would indicate.
2) Space is limited especially on the 1hr forecast, and I thought it was important to keep the vertical height same for all the forecast, but it might be possible to shoehorn it into the 3hr and 24hr intervals.

Any thoughts?

Michael

         "windDir":"NW",
         "windDirDEG":310,
         "windDirMax":"NNW",
         "windDirMaxDEG":340,
         "windDirMin":"NW",
         "windDirMinDEG":310,

         "windDir80m":"NW",
         "windDir80mDEG":325,
         "windDirMax80m":"N",
         "windDirMax80mDEG":349,
         "windDirMin80m":"NNE",
         "windDirMin80mDEG":17,

Probably

**Comment by NickB1** [comment]
Hi Michael, thanks for the reply!

I didn't know it was possible to show 1hr and 3hr forecasts.
Is there any documentation about that?

I was thinking about a vane or a cardinal notation in the 24h forecasts showing the average wind direction of the day.

Nick

**Comment by michaelundwd** [comment]
Hi Nick

Take a look at  the #455 that contains the documentation and code to download for the additional 1hr and 3hr interval forecasts.  To see what it looks like see http://lordshipweather.uk

As this is still a PR and not yet merged into the master, you might want to wait until it is if you don't want to move away from the "official" version.

I agree that cardinal might be a good idea, but need to find out how Aeris calculate the mean for a day; I don't know how quickly the wind direction can change.

Michael

**Comment by robwolff3** [comment]
I would also really appreciate wind direction forecast. Would save me from having to look up the forecast separately on AerisWeather or weather.gov.
