### ISSUE TITLE
Issues with README.md

### ISSUE THREAD

**Issue by captain-coredump** [poblabs/weewx-belchertown#50]
Two issues with instructions in README.md, both in the [MQTT (for Real Time Streaming) Options](https://github.com/poblabs/weewx-belchertown#mqtt-for-real-time-streaming-options) table:

1. mqtt_port description calls it "The MQTT broker's port."  A clearer description would be "The MQTT broker's **_websocket_** port," and give *anything* but the non-websocket 1883 as an example.

2. disconnect_live_visitor is actually disconnect_live**__website_**_visitor in the skin's code.  Pulled out a few of my remaining hairs trying to figure out why my setting (0) didn't stop the disconnects.

FWIW, the skin is otherwise working nicely for me with a local mosquitto instance, and is quickly becoming my favorite weewx data viewer.....

**Comment by poblabs** [comment]
All makes sense! I'll get that updated. 

Thanks for the clarification. I've stared at the readme for hours hoping it was clear enough. There's always room for improvements. 

Changing the variable name might not be the best option since it'll break websites. Do you think a clearer description would help instead?

**Comment by poblabs** [comment]
Interesting and you're probably right - it is broken and not reported. I'll take a look at it

**Comment by poblabs** [comment]
Fixed! Thanks again
