### ISSUE TITLE
Darksky 8-day forecast wind speeds

### ISSUE THREAD

**Issue by captain-coredump** [poblabs/weewx-belchertown#51]
The wind speeds in the Darksky 8-day forecast seem to be suspiciously high on both my site and the Belchertown site.

FWIW, these are my settings in weewx.conf:

            darksky_lang = en
            darksky_units = us

The units are displayed as MPH, but the numbers themselves seem to be in the ballpark for KPH.....

**Comment by poblabs** [comment]
I wonder if the DarkSky wind forecast is for the Wind Gust? 

If I look at Windy.com's forecast model, the wind gust matches (within margin, maybe, sort of?)...

How does yours compare to windy? 

![image](https://user-images.githubusercontent.com/3484775/51446212-ef055e00-1cdc-11e9-9dee-ad696ccc7730.png)

![image](https://user-images.githubusercontent.com/3484775/51446217-fa588980-1cdc-11e9-866f-4fab5f472df5.png)

**Comment by captain-coredump** [comment]
When I just looked at index.html.tmpl, it is indeed using the windGust and not windSpeed from darksky.  That explains the high numbers, many of which would have prompted NWS alerts if they were sustained.

I have seen the icon for wind that you used in the forecast table used as a gust icon in other web sites, so I guess it is technically 100% accurate in what it is displaying (gust forecast).  I don't see a wind sock icon in the set though, which is used for regular wind speed along with the gust icon.  It would be nice to have:

windsock-icon    windSpeed  units
wi-strong-wind   windGust    units
(aka: gust-icon)

I was just looking at windy.com, and they use the same two sock and gust icons backwards on their map.  So much for "standards" in icons!

Anyway, I just slapped this into my index.html.tmpl, and it doesn't look half bad (read: overflow the forecast cell) to this non-graphic-artist:

output_html += '<i class="wi wi-strong-wind"></i> '+ parseFloat( data["daily"]["data"][i]["windSpeed"] ).toFixed(0) + '$unit.label.windSpeed' + " G " + parseFloat( data[
"daily"]["data"][i]["windGust"] ).toFixed(0);

I don't know if it is better to leave the page as-is using windGust, change it to windSpeed, or make it  configurable option in weewx.conf.  In any case, my concern has been addressed by finding out that the values displayed are the gusts, and you can close this issue.....

**Comment by poblabs** [comment]
I haven't had a chance to dig into it, so thanks for looking under the hood. The NWS alerts aren't triggered by the wind gust observation - they're embedded in the data download that comes from DarkSky. So while the website is "just showing what's in the data" - I'm not sure how DarkSky is triggering the multiple alerts. It should be done from some NWS data - but the duplicates we all had yesterday didn't make sense. 

It also makes me wonder if DarkSky has made a change recently because I haven't changed the wind forecast yet it's reading much higher than the other day. 

I guess I'm not sure if I should include 2 wind rows in the forecast which could cause confusion, or see if both can fit on 1 line? or make it an option to show one or the other?

If I did both on 1 line, it looks like:

![image](https://user-images.githubusercontent.com/3484775/51490584-bf586380-1d79-11e9-9cd1-d892e6a58143.png)


With a little styling, it should work like this - but I haven't tested it on all devices. 

![image](https://user-images.githubusercontent.com/3484775/51490601-cbdcbc00-1d79-11e9-8547-81d7548a5f16.png)

What do you think?

**Comment by captain-coredump** [comment]
With the alerts, I was referring to the NWS sending them out
through their alert system if Darksky's forecast was accurate.
Darksky was showing gale and tropical storm winds for 5 of
the 8 days in yesterday's forecast.  (On a side note, the skin's
alerts worked great here yesterday for the storm!)

I have no preference in the layout, except trying to save screen
real estate since my primary viewer is a $49 wall-mounted Amazon
Android tablet that I use for a weather station console.  I could
live with using the windy.com G: notation for the sake of brevity,
like they use on their wind needles:



Graphic/web design is not one of my strong points, so I will
defer the choice to you.....


-- 
Sent from my iEtch-a-Sketch via subspace

**Comment by poblabs** [comment]
In an effort to keep things consolidated and not use more screen-space, I am going to try this out for wind speed and wind gust...

![image](https://user-images.githubusercontent.com/3484775/51990008-24950e80-2476-11e9-92bc-b657a8917499.png)
