### ISSUE TITLE
New issue(s) with PR #590 (Use Weewx Daily Summaries for charts where "aggregate_interval" >= 1 day)

### ISSUE THREAD

**Issue by ArendPWS** [poblabs/weewx-belchertown#627]
New issue(s) with PR #590 (Use Weewx Daily Summaries for charts where "aggregate_interval" >= 1 day)

I created six test charts. The first screenshot shows the charts created with the original code by @poblabs.
The second screenshot shows the same charts created with latest 1.3b1 which fails to generate the 4th and 5th chart. There are also differences in the 6th chart. Here is the graphs.conf entry I used to produce the charts.

		[testcharts]
		# Chart Timespan Defaults
		title = "Test charts using outTemp and rainTotal"
		show_button = true
		button_text = "Test charts"
		type = spline
		aggregate_type = max
		aggregate_interval = 86400 # 1 day

		[[All_years]]
			title = "All years with xAxis_groupby = year and xAxis_categories is none"
			time_length = all
			gapsize = 86400000
			xAxis_groupby = year
			[[[outTemp]]]
				name = Max Temperature
				yAxis_label = "Temperature (℃)"
				zIndex = 2
				color = "#fc0404"
				[[[[marker]]]]
					enabled = true
					radius = 4
			[[[outTemp_min]]]
				name = "Min Temperature"
				observation_type = outTemp
				aggregate_type = min
				zIndex = 2
				color = "#173c6a"
				[[[[marker]]]]
					enabled = true
					radius = 4
			[[[rainTotal]]]
				type = column
				name = Rain Total
				yAxis = 1
				zIndex = 0
				color = "#438bd6"

		[[2020_climate]]
			title = "Climate 2020 with xAxis_groupby = month and xAxis_categories"
			time_length = year_specific
			year_specific = 2020
			gapsize = 86400000
			xAxis_groupby = month
			xAxis_categories = 'Jan', 'Feb', 'Mrt', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'
			[[[outTemp]]]
				name = Max Temperature
				yAxis_label = "Temperature (℃)"
				zIndex = 2
				color = "#fc0404"
				[[[[marker]]]]
					enabled = true
					radius = 4
			[[[outTemp_min]]]
				name = "Min Temperature"
				observation_type = outTemp
				aggregate_type = min
				zIndex = 2
				color = "#173c6a"
				[[[[marker]]]]
					enabled = true
					radius = 4
			[[[rainTotal]]]
				type = column
				name = Rain Total
				yAxis = 1
				zIndex = 0
				color = "#438bd6"

		[[Month_Day]]
			title = "Month february 2020 with xAxis_groupby = day and xAxis_categories is none"
			time_length = month_specific
			year_specific = 2020
			month_specific = 2
			gapsize = 86400
			xAxis_groupby = day
			[[[outTemp]]]
				name = Max Temperature
				yAxis_label = "Temperature (℃)"
				zIndex = 2
				color = "#fc0404"
				[[[[marker]]]]
					enabled = true
					radius = 4
			[[[outTemp_min]]]
				name = "Min Temperature"
				observation_type = outTemp
				aggregate_type = min
				zIndex = 2
				color = "#173c6a"
				[[[[marker]]]]
					enabled = true
					radius = 4
			[[[rainTotal]]]
				type = column
				name = Rain Total
				yAxis = 1
				zIndex = 0
				color = "#438bd6"

		[[Month_Hour]]
			title = "Month february 2020 with xAxis_groupby = hour and xAxis_categories is none"
			time_length = month_specific
			year_specific = 2020
			month_specific = 2
			gapsize = 3600
			xAxis_groupby = hour
			[[[outTemp]]]
				name = Avg Temperature
				aggregate_type = avg
				yAxis_label = "Temperature (℃)"
				zIndex = 2
				color = "#f7a35c"
			[[[rainTotal]]]
				type = column
				name = Rain Total
				yAxis = 1
				zIndex = 0
				color = "#438bd6"

		[[Day_Hour]]
			title = "Day 23 february 2020 with xAxis_groupby = hour and xAxis_categories is none"
			time_length = day_specific
			year_specific = 2020
			month_specific = 2
			day_specific = 23
			gapsize = 3600
			xAxis_groupby = hour
			[[[outTemp]]]
				name = Avg Temperature
				aggregate_type = avg
				yAxis_label = "Temperature (℃)"
				zIndex = 2
				color = "#f7a35c"
			[[[rainTotal]]]
				type = column
				name = Rain Total
				yAxis = 1
				zIndex = 0
				color = "#438bd6"

		[[Year_Day]]
			title = "Year 2020 with xAxis_groupby = day and xAxis_categories is none"
			time_length = year_specific
			year_specific = 2020
			gapsize = 86400
			xAxis_groupby = day
			[[[outTemp]]]
				name = Avg Temperature
				aggregate_type = avg
				yAxis_label = "Temperature (℃)"
				zIndex = 2
				color = "#f7a35c"
			[[[rainTotal]]]
				type = column
				name = Rain Total
				yAxis = 1
				zIndex = 0
				color = "#438bd6"

Created with original code:

![Test_charts_with_orginal_code](https://user-images.githubusercontent.com/67259651/110702463-d45f0d80-81f2-11eb-80d5-9eb1a07a289c.png)

Created with 1.3b1:

![Test_charts_with_optimized_code](https://user-images.githubusercontent.com/67259651/110705202-5866c480-81f6-11eb-803a-a168d635abb5.png)

**Comment by michaelundwd** [comment]
I have been doing something similar, so your observations are very welcome.
My analysis of your data:
The first 3 charts are the same in both cases.  The xAxis-groupby is >= 1 day that is the aggregate interval of 86400 that is used to select the daily charts
Charts 4 & 5, the xAxis_groupby is < 86400, so it cannot resolve xAxis_groupby items < 86400
Chart 6 has me puzzled and is similar to the issues I have been trying to resolve with totalRain.

Now to what I have been doing.  I wanted an overall climate summary for all years, with average min and max temperatures and average monthly rainfall, which I was not getting.  I am working on a PR to do that using the min and max temperatures in archive_daily_rain and a complex sql query for the rainfall.  I cross-check all the data used in my graphs against an Access database using weewx.sdb as a source.  I will have a look at your chart 6 to see if I can come up with an explanation.

Charts 5 & 6 could be fixed by making the criteria for using the daily summaries restrict the xaxis_groupby perhaps.
Michael

**Comment by michaelundwd** [comment]
@ArendPWS 
I'm having difficulty replicating your results.  I removed the changes for using the daily summaries and I get the same results for all charts.  What version of "original code of @poblabs" did you use?
Could you attach it so I can take another look please?

**Comment by michaelundwd** [comment]
@Arendpws Observations on your data Issues

Details summarised in attached workbook

[Arend_year_dayData.xlsx](https://github.com/poblabs/weewx-belchertown/files/6135146/Arend_year_dayData.xlsx)

Charts 1 to 3 are ok
Charts 4 & 5 are trying to look at data at a finer resolution than the daily summaries allow
Chart 6 gives slightly different results with my data because in sql_lookup definition the date range is >= 01/02/202 and <= 01/01/2021.  I think it should be < 01/01/2021. When I corrected that the discrepancy disappears.  I had a lot of trouble resolving this as I was getting different results in Access and sqlite.  sqlite queries showed that the archive_day tables do contain the correct values.  Do you know if your daily summaries are correct?  You can always send me a copy of your database if you still have a problem.
  
I used the following as a first check and subsequently refined it

sqlite /home/weewx/archive/weewx.sdb
sqlite> select avg(outTemp) from archive where strftime("%Y-%m", dateTime,'unixepoch','localtime')=='2020-11';
sqlite> select sum(sum)/sum(count) from archive_day_outTemp where strftime("%Y-%m",dateTime,'unixepoch','localtime')=='2020-11';
sqlite> select sum(wsum)/sum(sumtime) from archive_day_outTemp where strftime("%Y-%m",dateTime,'unixepoch','localtime')=='2020-11';

see https://groups.google.com/g/weewx-user/c/8qrEe1bN8Yo/m/O3PE9_0NAwAJ

I will propose a PR that will do the following, but will outline the proposal here in case anyone can spot what problems it might cause elsewhere - comments welcome specially on 2!

1 Introduce additional criteria to prevent the daily summaries being used if the detail required is at a finer resolution than daily
2 Change the sql_lookup definition such that for instance; dateTime <= {5} becomes dateTime < {5}
This may have some unforeseen implications that it would be nice to catch early.

Incidentally, the the benefits of using the daily  summary tables where possible reduced the time to carry out Arend's test charts from 88 secs to 5 secs on my original Raspberry Pi B.  Thanks @Mattk70

**Comment by ArendPWS** [comment]
@michaelundwd,

Hi Michael thank you for all your time and effort. I opened this issue as a reference for future solutions.

As I mentioned in a previous conversation with you my goal is to get rid of the "direct **" sql queries. I am working on a solution that uses the XType member functions get_series() and/or get_aggregate(). This would allow for users to plot charts using (user-defined) XTypes that are not stored in the database (I am using three XTypes at the moment myself from which only one is stored in the database). Clinging on to "direct **" sql queries would mean that users are forced to store their XType in the database. That would be the "unfriendly" option.

One issue I have at the moment with my current solution is in the way grouping has been defined by Pat with his original code. Another issue with my current solution is that there probably will be no room for optimizations in the Belchertown skin because all of the quering is handled internally by the (user-defined or WeeWX) XType.

I hope this has clarified some of the issues I am working on. But please continue your efforts to solve the current issues with these charts 👍, we really need to solve this and I am not sure if my ideas will be viable.

Input from other users with brilliant ideas is allways welcome.

** With "direct" I mean the sql queries in their present form for this group-by charts.

**Comment by michaelundwd** [comment]
@ArendPWS 
Thanks for your update - I did wonder about the semantics of some of your tests!

It was essential for me to check out your concerns as I am using the daily summaries to calculate average rainfall, max and min temperatures - work in progress!  I will issue a PR in a day or two for the changes to fix these specific issues and any others I uncover regarding the use of daily summaries.

I will leave you to ponder the use of XTypes  and hope that performance on my Pi will not fall through the floor should they be implemented!

Michael

**Comment by ArendPWS** [comment]
@michaelundwd

Today I checked the weewx-development group and found that Tom has released 4.5.0 alpha some days ago.

[https://groups.google.com/g/weewx-development/c/Ptqs4dw-71s](https://groups.google.com/g/weewx-development/c/Ptqs4dw-71s)

The changes he mentions include this one:

> Improved performance when calculating series using aggregation periods that are multiples of a day.

This does sound like Tom has started trying to implement optimizations using daily archives. At the moment the optimizations only appear to support SQLite, but this is an alpha release ofcourse.

[https://github.com/weewx/weewx/commit/0458b00e40cd084efefb41538455ce32961062d3#](https://github.com/weewx/weewx/commit/0458b00e40cd084efefb41538455ce32961062d3#)

**Comment by michaelundwd** [comment]
@ArendPWS 
Well spotted and thanks for letting me know - that could be really useful, in reducing the amount of work if nothing else. 

I had only just discovered some useful functions in weeutil.py (like isStartOfDay()) and had not managed to find the sql ones yet.  It looks as if there is some use of daily archives already in the current xtypes.py, but he appears to be adding to the criteria for selecting use of the daily archive.  They are not straightforward as my attempts and his code reveal.  

The criteria for use of the daily archive in Belchertown are currently incorrect as they refer to aggregate_interval that plays no part in the sql queries.  

This raises some issues:

1. Is it worth putting some effort in to improve the belchertown criteria and issuing as a PR?  I think the answer to that is Yes.
2. Is it worth developing the sql_lookup code to give what I was looking for (eg average monthly maximum temperature, average monthly rainfall)?  I was looking to make that more generic.  I already have the code for these specific examples, but a more generic solution is quite tricky.  I think the specific ones might be worth doing, but whether it is a PR or not?
3. To make use of the forthcoming weewx functionality would mean some significant changes to belchertown.py.  How much effort would that be?  If @pob is reading this, perhaps he could comment on why he did not use the inbuilt weewx functions originally.  I suspect it is because at the time he wrote the skin, there was limited weewx archive functionality.

I'd welcome your thoughts, as well as anyone else's.

Michael
