### ISSUE TITLE
Getting "Maps Overlimit" notification from AerisWeather

### ISSUE THREAD

**Issue by iamdadzilla** [poblabs/weewx-belchertown#647]
I am getting Belchertown set up, so there is no traffic to my site other than me. I have MQTT running. The email alert from AerisWeather says I am using over 3000 "map units" and hitting my quota. Is it possible that MQTT is querying the AerisWeather API at each refresh?

**Comment by poblabs** [comment]
Mqtt should not be pinging aeris, they aren't connected. What's your aeris
refresh rate?

**Comment by uajqq** [comment]
I get this when I'm making changes to my site or setting something up--I hit overlimit because I keep having to refresh or restart the skin. When running it normally I don't have any issues. 

However, it occurs to me that there's no "stale" check for the map image the way there is for the forecast data, which would help this issue. I'll see if I can get that working.
