### ISSUE TITLE
Rainfall total error on records page

### ISSUE THREAD

**Issue by jdb235** [poblabs/weewx-belchertown#690]
**Describe the bug**
The records page for my station shows an incorrect rainfall total for this month (which is the month with the highest rainfall so far). The NOAA report (screenshot below) gives a rainfall total of 173.6 mm, and this is the same total that's given on the console. On the records page, however, it gives 169.93 mm (screenshot below).

I guess this may be an issue with units/rounding somewhere, as the station is a UK one which has a 0.2 mm tipping bucket so totals must always be a multiple of 0.2 mm, but I'm not sure where this would be defined.

**Version of the skin you're using**
1.2

**Screenshots**
![noaa_rainfall_may](https://user-images.githubusercontent.com/79938996/119340705-c74aaa00-bc8a-11eb-949d-f813a7047f54.png)
![belchertown_rainfall_may](https://user-images.githubusercontent.com/79938996/119340703-c6b21380-bc8a-11eb-9560-ed1161502e6a.png)

**Comment by James-76** [comment]
You are correct in working out what is going on and it is all linked back to weewx.

This is because weewx converts back to the default units for the database, which is most cases is US.   This means that 0.2mm is converted to inches.

In most cases this isn't a problem but over a month / year you then get into rounding errors like you see.

Honestly there is no easy way to solve this.

You can convert the weewx database into METRIC but again the can introduce some conversion issues as weather stations I believe will normally output in US units even if being displayed in metric so everything is being converted so it can be stored ie F -> C.

James

**Comment by jdb235** [comment]
Thanks for the explanation. It's not a major problem so I'll probably just leave it as it is for now.

As a side point I've also got the colour coded month-by-month tables from fuzzy-archer on my records page and the monthly total in that month is correct, so I guess this must be querying the database in a different way?

**Comment by James-76** [comment]
Have you got a link to your website? 

I'm also based in the UK and have a 0.2mm bucket.

I've also set up fuzzy archer code so happy to dig a bit more.

Can you also confirm you are using US for your weewx database.

James

**Comment by James-76** [comment]
There is something clearly wrong here, because your 'total' rainfall of 197.8mm is close to what you would have got around May time.   I hit that value around the middle of May here in Guildford so it is clear the sql queries are no longer processing any rain fall since late May / early June

Assuming you are using sqlite3;

sqlite3 /home/weewx/archive/weewx.sdb
sqlite> SELECT strftime("%m", datetime(dateTime, "unixepoch")) as month, strftime("%Y", datetime(dateTime, "unixepoch")) as year, ROUND( SUM( sum ), 2 ) as total FROM archive_day_rain GROUP BY month, year ORDER BY year;

What happens to the last few results?

02|2021|1.37
03|2021|0.92
04|2021|0.2
05|2021|3.07
06|2021|2.02
07|2021|2.6
08|2021|1.8

**Comment by jdb235** [comment]
Ah, that's because the station has only been recording since mid-March, and there wasn't much rain from then until May (that screenshot was taken towards the end of May). The year total to date is now shown as 430.2 mm - curiously though, the all time record (which is this year, of course) is shown as 430.28 mm. These are the month-by-month totals:

03|2021|0.36
04|2021|0.73
05|2021|7.02
06|2021|3.78
07|2021|3.61
08|2021|1.43

This seems to be where the problem is coming in - converting 7.02 inches to mm gives 178.31 mm, which is what is shown in the Belchertown records table for May. I'm still confused as to how the fuzzy archer tables arrive at the correct value though? It's also strange that the 2021 total in the records table is correct, given that adding up the above values and converting to mm gives 430.02 mm.

**Comment by James-76** [comment]
I think it is probably linked back to the SQL query and rounding within belchertown.py queries.  Rainfall according to my database was as follows

The one at the top is the one in belchertown.py.

```
sqlite> SELECT strftime("%Y", datetime(dateTime, "unixepoch")) as year, ROUND( SUM( sum ), 2 ) as total FROM archive_day_rain GROUP BY year ORDER BY total;
2021|15.08
2018|17.89
2017|22.29
2016|22.36
2019|22.81
2020|26.23

sqlite> SELECT strftime("%Y", datetime(dateTime, "unixepoch")) as year, ROUND( SUM( sum ), 4 ) as total FROM archive_day_rain GROUP BY year ORDER BY total;
2021|15.0787
2018|17.8879
2017|22.2856
2016|22.3583
2019|22.811
2020|26.2345
```

26.23 converted to mm gives you 666.242mm  
26.2345 converted gives you 666.3563mm which when rounded back to 1 decimal place gives you 666.4mm which matches to what fuzzy archer gives me.

![image](https://user-images.githubusercontent.com/59254774/130828390-584b1958-b832-49a5-924c-bae2e64e971d.png)

I think we need to alter the sql queries in belchertown.py to stop these double rounding errors.

**Comment by James-76** [comment]
I proved this is the issued because it rained here on 1st August with 2.4mm of rain falling.

Existing;
sqlite> SELECT strftime("%m", datetime(dateTime, "unixepoch")) as month, strftime("%Y", datetime(dateTime, "unixepoch")) as year, ROUND( SUM( sum ) * 25.4, 1 ) as total FROM archive_day_rain GROUP BY month, year ORDER BY year
08|2021|45.8

Addition of "localtime";
sqlite> SELECT strftime("%m", datetime(dateTime, "unixepoch", "localtime")) as month, strftime("%Y", datetime(dateTime, "unixepoch", "localtime")) as year, ROUND( SUM( sum ) * 25.4, 1 ) as total FROM archive_day_rain GROUP BY month, year ORDER BY year;
08|2021|48.2

Will submit pull request.

**Comment by jdb235** [comment]
I just implemented these changes and the record is now showing the correct amount. Many thanks!
