### ISSUE TITLE
Yearly Wind Direction Graph Values

### ISSUE THREAD

**Issue by michaelundwd** [poblabs/weewx-belchertown#71]
0.9 installed and working well thank you, except for one issue.
The yearly wind direction graph is showing a predominant wind direction of between West and North for February, but the monthly one for February shows my more normal predominant wind direction as being between South and West.  Two screen shots attached, with actual values for 20 Feb.  Any thoughts?

![winddirection_2019](https://user-images.githubusercontent.com/45148992/53693694-f586fb00-3d9b-11e9-9706-3aee1b32d0cc.jpg)
![winddirection_feb2019](https://user-images.githubusercontent.com/45148992/53693696-f7e95500-3d9b-11e9-91e1-bcb0a3086b46.jpg)

**Comment by poblabs** [comment]
Looks like the wind direction for [month is using the "average"](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown_highchartsSearchX.py#L735) whereas [year is using the "max"](https://github.com/poblabs/weewx-belchertown/blob/master/bin/user/belchertown_highchartsSearchX.py#L1031) for the weewx built in vector lookups. 

Day lookups aren't aggregating, and week lookups are using "max" as well. 

Now I'm questioning which one is correct? Maybe no aggregation?

**Comment by biltmorelaker** [comment]
Different settings of max vs. average for the different periods is analogous to the different choice of calendar vs rolling periods that I note in my Issue #66 Feature request:

> "Currently the main page shows graphs since midnight, as does the Today choice on the Graphs page. The Week and Month choice on the Graphs page are the most recent 7 and 30 days respectively, while the Year choice is since Jan 1." 

Today and Year are calendar-based, while Week and Month are rolling. 

For calendar-based vs rolling of the period covered by the graph, I vote for user choice.

For wind direction, I would prefer average. But here is the problem:
There is a setting which will have WeeWX record the last wind direction if the wind speed is 0. For those who use that setting, average is skewed, since records with no wind speed will have a direction that isn't real. So for wind direction I vote max or user choice (I prefer the latter).

**Comment by poblabs** [comment]
@biltmorelaker For the user choice, would they choose for all 4 graph timeframes or just for month and year? or? 

I haven't had a chance to work on your other feature requests yet. Been tamping down fires with 0.9 😃

**Comment by biltmorelaker** [comment]
@poblabs How about you just replace windirplot with winddiravgplot and add windmaxplot as another of the choices for highcharts_graph_1 through highcharts_graph_6? If they choose the former, all of the timeframes would show the average direction. If they choose the latter, the graphs for all would show the max.

I believe that weewx aggregates across the LOOP data when writing each archive record. So the Today graphs points are "aggregates" even though each record is displayed. For week, month and year, you need to plot a variable that aggregates that data.
Does that make sense?

Regarding my feature requests, I actually figured that you'd consider them for version 1.0. So no rush.

**Comment by poblabs** [comment]
@biltmorelaker Your suggestion isn't a bad one, but I got to thinking about this the last couple of hours and I think "average" is what should be selected for the wind gust vector. 

I recall somewhere in the forums someone (maybe gjr80) mentioning that "max" for windgust will almost always be North, in the neighborhood of 355 degrees, if there was any wind in that direction that day. Which probably explains why Month is average, but year isn't (I probably never went back and fixed it).

**Comment by michaelundwd** [comment]
Thanks for the explanation, but I think the right answer may not be trivial.  Both average and maximum have flaws and neither take account of whether the wind is blowing or not.  The maximum value will always show a bias towards the North-West, as it will chose the greatest value less than 360.  The average will produce misleading results, eg average of 350 and 10 is 180, whereas it should be 0 (or 360).  I had a look to see how others have addressed the issue. eg

https://en.wikipedia.org/wiki/Directional_statistics
http://blogs.itron.com/computing-a-weighted-average-wind-speed-and-wind-direction-across-multiple-weather-stations/
https://www.researchgate.net/publication/262766424_Technical_note_Averaging_wind_speeds_and_directions
https://control.com/thread/1026210133

From what I can understand, we are dealing with a circular function, hence circular maths is required. The simplest formula would appear to be atan2(mean of cosine(wind direction), mean of sine(wind direction)); not sure how that relates to available functions in python and whether it is worth the effort.

If asked to make a choice, I would go firstly for consistency across all time periods, then user choice.  If user choice is not an option, I would go for average.

**Comment by poblabs** [comment]
Hey guys, 

I agree that I should normalize on average for now to keep it all consistent out of the gate.

The original highcharts code comes from gjr80 but at this point it’s heavily edited. I mention this because with the original code, it was using weewx’s [getSqlVectors()](https://github.com/weewx/weewx/blob/e94ad3c608b61f77e7b8b974eb68aecf126a8dc5/bin/weewx/manager.py#L468) which is where you can set the `aggregate_type` (avg, max, sum, etc). 

If you [take a look at the code here](https://github.com/weewx/weewx/blob/e94ad3c608b61f77e7b8b974eb68aecf126a8dc5/bin/weewx/manager.py#L505), you’ll see it’s doing some special things with wind. Including [some cosine math](https://github.com/weewx/weewx/blob/e94ad3c608b61f77e7b8b974eb68aecf126a8dc5/bin/weewx/manager.py#L594), and if we select [Average aggregation, it’s doing a complex() math](https://github.com/weewx/weewx/blob/e94ad3c608b61f77e7b8b974eb68aecf126a8dc5/bin/weewx/manager.py#L625) on those observation values. I can’t pretend I know what complex() is. 

So maybe the real answer is to select average for windDir since the math is already built into weewx?

**Comment by biltmorelaker** [comment]
@michaelundwd Very interesting reading. Thanks for the references.

There is a nice discussion on measuring averages of wind speed and direction in the "Weather Observer's Handbook", by Stuart Burt. Unfortunately, I don't know of an online version of the book. He points out that there are two ways that weather station loggers, themselves report wind directions over each logging interval - the 'modal' method and the 'vector mean wind' approach. Davis devices, he says, use the former. They have 16 compass directions and report the one with the highest frequency over the logging period. He says the 'vector mean wind' method is more accurate and uses a calculation he makes available in this downloadable Excel spreadsheet - [http://measuringtheweather.com/wp-content/uploads/2012/05/Appendix-2-Vector-mean-wind-Excel-spreadsheet-example.xlsx](http://measuringtheweather.com/wp-content/uploads/2012/05/Appendix-2-Vector-mean-wind-Excel-spreadsheet-example.xlsx) He also has a macro version.

The book also says that

>  "Statistical summaries of wind speed and direction normally consist of hourly, daily, monthly, and annual tabulation. For hourly summaries, the modal or vector mean direct, scalar mean speed...are usually quoted. For daily, monthly or annual summaries, the vector mean wind (direction and speed) along with the scalar mean speed, the hourly scalar mean wind speed and its direction with date and hour of occurrence...are the norm". He states that wind roses are a "more graphical means of expressing the frequency of various wind direction and speed combinations over time."

So we have two issues.
1. What should be plotted and how should it be represented graphically
2. How to calculate it the data for 1

@poblabs Regarding 2 you point out that Highcharts is doing math to get aggregated data to plot. It might be worth asking gjr80 about that math so people will know what they are seeing. You could also ask gjr80, mwall and tkeffer if there are other aggregations available in the weewx toolbox.

Regarding 1, I agree with Pat's choice about average for all plot periods. However, Should a wind rose chart be used instead of Highcharts for wind direction? I'm guessing that there is a no-cost wind rose generator available. So maybe something to consider long range for a future version.

**Comment by poblabs** [comment]
Let's keep in mind that the skin is just a report output which employs the built-in weewx values and functions. Sometimes I get the combination wrong so it's a matter of understanding the tools in the underlying code to find the right combination. So any changes to calculation should probably be a discussion on the user forums. I'm sure Tom and Matthew already have a lot of this covered. 

For the highcharts math, it's actually math done inside of weewx's toolbox already. The skin is just "requesting" it, converting it based on units, and applying some rounding based on the skin.conf, zipping it up for the JSON payload to be displayed. Having a look at those links I posted may help as I think that is the toolbox and it's well commented for reference. 

Gary had a windrose chart included in the original code, but I had removed it because at the time I didn't need it. When asked to make this skin public there's been no request for it so I've heavily back-burnered it. Looking at Gary's code for windRose, it looks like he's using the same getSqlVectors() command, but with "[vecdir](https://github.com/weewx/weewx/blob/e94ad3c608b61f77e7b8b974eb68aecf126a8dc5/bin/weewx/manager.py#L1136)" instead of windDir. I haven't seen vecdir before, but [looking at this line from the weewx codebase, it looks to be applying the atan()](deg = 90.0 - math.degrees(math.atan2(_row[1], _row[0]))) function Michael mentioned above. 

I'm reluctant to link to Gary's code here without his permission, but now I'm curious about vecdir and if that's what should be used.

**Comment by michaelundwd** [comment]
Latest commit I've just tested shows a more consistent view of wind direction across the different time periods.  Thanks.

Hopefully vecdir is the ultimate solution - it looks promising from the code segments you referenced.  Its encouraging that all the hard work appears to have been done by gjr80, mwall and tkeffer; as you say a matter of picking up the right data analysis hooks for the skin.

**Comment by kjames79** [comment]
Where are we with this at this point? I am noticing that in year view all of my wind direction points are north. If I am reading these comments correctly, by default for year it's set to max wind direction. If I wanted that to be averages instead of max I would need to make a change in highcharts? I see it's been a few years since this post. Any help is appreciated. 


just as I was about to collect screenshots I noticed that this seems to be happening right on down to week view. I'm starting to get the impression that it is set to averages however, as a commenter here had stated, averages is flawed in that it accounts for direction when the wind speed is zero. I assume then that is still an issue.
