### ISSUE TITLE
Adding www to url stops charts from appearing

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#74]
Not sure if this is exactly an issue or not. May be a setup problem

My site url is set as 41south.net.nz and all is well, if however I (or anyone else who might put www in front of everything) use www.41south.net.nz the the charts do not appear. 

Your home site does the same thing :)

**Comment by poblabs** [comment]
This is because the `belchertown_root_url` is set for non-www, so the JavaScript is getting blocked because of "cross origin loading". 

I thought this on my drive home today. My initial answer was to redirect 301 www to non-www (my site does that, how did you sneak in to a www?) 😄 Technically [you should choose 1 layout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Choosing_between_www_and_non-www_URLs), then [redirect the other](https://stackoverflow.com/a/35152933/1177153) so they're both covered. 

This brings up a larger issue of the use of `belchertown_root_url`. Explicitly defining the URL of your site has always been a thorn in my side. It's needed for subdirectory installations though (e.g. mysite/belchertown or mysite/weewx/belchertown or something). Specifically the nav menu will fail, everything else will work. I've had this as a long task item to figure out.

So I think the answer is to put a redirect in the header of the HTML which will force redirect anyone who arrives to the site to the `belchertown_root_url` instead. Seems really ugly though. 

Let me keep thinking about this. Maybe a change to the `header.html.tmpl` with some if/else's around the nav menu. 

Then I could do away with `belchertown_root_url` all together I think. 🤔

**Comment by 41south** [comment]
So should I set the url as www.41south.net.nz or does that still end up with the same cross origin problem?

I only found this as I'm changing to a short url of 41south.nz (dropping the .net bit) which already points to my home IP address

**Comment by poblabs** [comment]
Same problem. I'd choose one or the other, as mentioned in those links, as
a best practice.

**Comment by poblabs** [comment]
I'm going to close this since it's not a skin-related item. It's more of a decision you need to make to have www or non-www as your primary for the site. 

Website suits like WordPress handle the forwarding for you with htaccess or PHP, weewx doesn't have that ability, so it's up to the server owner to make those modifications (see below). 

I could add an option for "force non-www" but that could be confusing. If you think it makes sense I could add it in which would put the code below in the header.

Otherwise, I might just add a FAQ answer which would have users put this into header.html.tmpl if they want to force non-www.

Right above the `</head>` in header.html.tmpl

```
<script type="text/javascript">
if (window.location.hostname.indexOf("www") == 0) {
    window.location = window.location.href.replace("www.","");
}
</script>
```

[Found from here](https://stackoverflow.com/a/47281530/1177153). This redirects anyone who went to your site as www, and sends them to non-www.

**Comment by 41south** [comment]
Thanks Pat, no worries at all, I like the FAQ idea though.
