### ISSUE TITLE
Relative url instead of absolute ?

### ISSUE THREAD

**Issue by bonjour81** [poblabs/weewx-belchertown#93]
Hi ! 
Today I discovered an issue with $belchertown_root_url  label.
So far, weewx generate the output files on a local server. If requested, the files will be uploaded to a remote location (for example a webhosting service).
The user may use the local site at home ( http//192.168.1.xx/weewx ) but may use his internet site outside home (example http://mywonderfullPWS.org )

At 1st, I though I could just set $belchertown_root_url to "."... it works no so bad on home page and it will kind of convert absolute path to local path.
But other pages does not work with this trick (for example, record page is in a subdir and need to go back to /NOAA directory.... not possible with the "." trick.

Is there any reason to use absolute path for all internal files of the skin ?
Would it worth to change for relative path ?

I can try to help if you like (I mean work on this on my fork, no risk to damage anything :) )

**Comment by poblabs** [comment]
This comes up very frequently. I should write a FAQ on it. 😃 

You're welcome to try and implement Relative URLs, but been there; done that. 

You can try to fix it in your fork, but I've tried and so far it's required. Look at the [WordPress approach](https://core.trac.wordpress.org/ticket/17048) (this is where I came from). They use [an absolute base url](https://wordpress.stackexchange.com/a/159294/12920) and it works for them, on [more than 33% of known websites](https://w3techs.com/technologies/details/cm-wordpress/all/all). 

Take this example. I know this intimately because my development server is in a subfolder. I am victim to needing absolute pathing:

---
base url is http://mysite/weewx/

A `href="/about"` in this subdirectory will send you to http://mysite/about. This is wrong since my site is in the `/weewx/` subfolder. I need it to be http://mysite/weewx/about.

A `href="./about'` (notice the dot) in this subdirectory will send you to http://mysite/weewx/about. This works, right? Yes if you are on front page. Now that you're on the about page at http://mysite/weewx/about and you click `href="./about'` again you will be sent to http://mysite/weewx/about/about. See the double about `path`?

This is the same thing you've experienced in your issue, where subpages need to go back to their parent page and it doesn't *quite* work. 

This is where relative URLs fail. 

---

The CSS and JS files are loaded with `belchertown_root_url` for this exact reason as well. To make sure they are correctly loaded no matter where your site is located on your server (root or subfolder). 

If weewx was using PHP, then there's games we could play. But weewx uses Cheetah which generates flat file HTML so we have to play archaic games with URL pathing (and use a lot of JS). 

Absolute URLs prevent things from going sideways. Again, this is the WordPress approach that I have adopted (for the time being). It works albeit a pain in the ass.

**Comment by bonjour81** [comment]
Hi, thx for your answer! 

I'll give a try and keep you in touch if I can make it work :)

**Comment by bonjour81** [comment]
Hi!
I have made some modification for relatives url.
It works not so bad with the following limits/modifications:

- I moved all "pages" to root directory (for example 'records/index.html' become 'records.html')
- So far the graphics does not show up...but I'm no expert in js/py, so I have probably missed something in the  scripts.
