### ISSUE TITLE
Skin 1.0 rc7  'Today' records section missing todays date

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#96]
The section to the left is missing todays date?

![Screen Shot 2019-04-08 at 2 20 50 PM](https://user-images.githubusercontent.com/1725001/55694741-ad49a100-5a09-11e9-9bb5-5d7e4910e1cd.png)

_Originally posted by @41south in https://github.com/poblabs/weewx-belchertown/issues/92#issuecomment-480660878_

**Comment by biltmorelaker** [comment]
To confirm. I am missing today's date in that table also. I didn't notice it earlier.

**Comment by poblabs** [comment]
Interesting, why would that be? 

That field is populated by [JavaScript moment.js from belchertown.js](https://github.com/poblabs/weewx-belchertown/blob/development/skins/Belchertown/js/belchertown.js.tmpl#L322), so it's normal for it to be blank in index.html.tmpl. (sidebar: which is why I'm stuck on what to do with #65 with all the AJAX changes)

@biltmorelaker Your lab site just says "April 2019" for the day and not the date. Did you make changes?

Here's mine:

![image](https://user-images.githubusercontent.com/3484775/55723518-40b5ae80-59d7-11e9-904e-77e6e7541953.png)

**Comment by biltmorelaker** [comment]
Yes. I was playing. I copied the format from the Month table cell to the Day table cell to see if it was the format that was missing. That cause the Month display where today's day should be. I've since taken that format out.

Then I looked at my production site and no format is present for today's date, but, as you say, it works fine.

**Comment by biltmorelaker** [comment]
Also, I believe it was working for me on my lab site early this morning (but I may have been wrong). I did copy over the files you updated in your latest commit from last night a little while ago.

**Comment by poblabs** [comment]
I've got it. I made changes to the weewx_data.json, specifically adding the radar HTML to the JSON array. The number of commas and other data within that URL make it invalid JSON which is causing JavaScript to puke. 

Same issue with #94. 

I've never needed this data to help troubleshoot, but I had this thought that it may be helpful. I'll remove it since it's causing more problems than it's worth.

**Comment by poblabs** [comment]
Update your `skins/Belchertown/json/weewx_data.json` with the one in [that commit](https://raw.githubusercontent.com/poblabs/weewx-belchertown/59685e528e5df106d182f6bce69f0bca18bf57db/skins/Belchertown/json/weewx_data.json.tmpl) and you should be good to go. 

Let me know

**Comment by biltmorelaker** [comment]
Yes. That fixed it for me.

**Comment by 41south** [comment]
Perfect, love your work gentlemen 👍 

Closing

**Comment by biltmorelaker** [comment]
It's 100% @poblabs!
