### ISSUE TITLE
1.0 rc7 rolling graph - rain

### ISSUE THREAD

**Issue by 41south** [poblabs/weewx-belchertown#99]
I'll just pop this in as a placeholder for now, I have a screenshot at home to add, maybe @biltmorelaker can take a look and see if he has the issue as well.

I have my [homepage] graphs set at time of 45000 (circa 12.5hrs or so) so they basically provide a rolling graph. All the graphs work as expected except the rain. I had about 2.8mm total of rain showing the other day, it started about 4am and was finished around 9am. Initially when I changed from time=day to 45000 it looked ok with both the accumulated and mm/hr rain rate looking ok, but by about 9pm the graph showed 0 rain - almost like as the rain rate scrolled left the rain total came down too.
With a rolling time style of graph I would have expected the the rate to just scroll left and the total to remain at the 2.8mm until the rain reset at midnight. 
Is there some sort of calculation going within the graph itself? All other parts of the skin showed the correct accumulated total rain.

**Comment by biltmorelaker** [comment]
I only had about 15 minutes of rain totaling .08 in (~2 mm) today. So, I can't really tell if the total drops as the trace falls off the left side of the plot. We are supposed to get rain tomorrow, so, hopefully it will sustained and I can see if I experience the same effect.

I do, though, suspect that the graph will show the total over the period plotted, which would track with your description.

**Comment by biltmorelaker** [comment]
Okay. Here's my follow up. As I suspected, the "tooltip" you see when mousing over the plot of Rain Total indicates the total since the start of the chart, whenever that is. So, if you have a short period and the plot rolls off the left edge of the x-axis, any accumulated rain total is not used in the value shown.

I believe that is what **should** be shown, as it is the most intuitive. When I look at a graph and see rain. I expect that the plot of the total would reflect rain that I see on the graph. I don't expect the totals totals to include rain beginning some time earlier and not shown.

Records for the day, though, should show a total since midnight.

**Comment by poblabs** [comment]
I would agree with that's how it should be shown. The [`rainTotal` is a custom Belchertown skin calculation](https://github.com/poblabs/weewx-belchertown/blob/development/bin/user/belchertown.py#L1179-L1188) (it really should be built into weewx I suppose?). Basically `rain` just shows bucket tips on the chart, `rainTotal `aggregates those bucket tips across the timespan of the chart.

So it's only totalling the last 12 hours on your chart. If 12 hours ago was 5am, then it won't calculate the rain you had at 4am since it's outside the time span window of rain lookups. Does that make sense?

**Comment by 41south** [comment]
Hmmmm, ok what do I use to show the total as it scrolls across until the
midnight reset?
I haven't struck a rolling chart doing this before.

**Comment by poblabs** [comment]
The way these rolling charts work are that the window is a finite amount of time. If you define that as 12 hours, then upon every update the database will only be polled for stuff within that 12 hour window. So as it keeps rolling, your data will keep getting pushed off to the left on every update. As a result, data that was pushed off won't be calculated since it's simply not aware of it's existance to calculate (the database didn't give it that data since it's outside the window of time you're looking for). 

So if you want to capture midnight, maybe you want a 25 hour window? Or maybe you don't want a rolling window for rain? 

*Interesting thought*: can rolling and non-rolling charts co-exist on the same page? Something to test.

**Comment by 41south** [comment]
They can it's what I've done. Gone back to the fixed "since midnight" for
rain only

**Comment by poblabs** [comment]
Hah awesome - I didn't even know I had added that feature 😉 Or maybe I did and this cold has me forgetting things. 

What's your graphs.conf look like for the non-rolling chart? Something like:

```
[homepage]
    # Chart Timespan Defaults
    time_length = 45000
    gapsize = 300000

    [[chart1]]
        title = Temperature
        [[[outTemp]]]
            zIndex = 1
            name = Temperature
        [[[windchill]]]
        [[[heatindex]]]
        [[[dewpoint]]]
            color = gray
    
    [[chart3]]
        time_length = today
        title = Rain
        [[[rainRate]]]
            yAxis = 1
        [[[rainTotal]]]
            name = Rain Total
```

**Comment by 41south** [comment]
Yep pretty much exactly that :)

**Comment by poblabs** [comment]
To confirm, the "since midnight" with `time_length = today` is working for you?

**Comment by 41south** [comment]
Yeah, this can be closed, thanks

**Comment by 41south** [comment]
Quick question - how does the [windrose] react with different time periods such as [day] [week] or shorter. I suspect that mine must be picking up the default 45000 (12.5hr) I have for [homepage] at the moment

**Comment by biltmorelaker** [comment]
I don't know the answer for sure. But I imagine that the Wind Rose graph acts the same way as other graphs with respect to the time_length over which it gathers its data. It does not aggregate data. However, it should include in the plot all of the data specified in:

1. The Observation-specific time_length (under [[[windRose]]]) or Chart-level time_length (under *e.g.* [[winplt]] - unlikely you'd specify both of these) if specified else
2. The Group-level time_length (under *e.g.* [week] if specified else
3. The Default time_length

@poblabs will know for sure
